### ISSUE TITLE
Unable to build with -DGL=1

### ISSUE THREAD

**Issue by thibaudk** [grame-cncm/guidolib#101]
Cmake will first trhow 2 warnings 

```
 CMake Warning:
   Value of GUIDOEngine_LIB_DEPENDS contained a newline; truncating

 CMake Warning:
   Value of jniGUIDOEngine64_LIB_DEPENDS contained a newline; truncating
```

and make returns this error

```
CMakeFiles/SGUIDOEngine.dir/flags.make:8: *** séparateur manquant. Arrêt.
make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/SGUIDOEngine.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

Builds fine without OpenGL support.

Tested on Ubuntu 19.10

**Comment by dfober** [comment]
The GL option is intended only to embed the opengl device. 
At first sight, the support is incorrect and probably for some time: it's looking for the opengl device in the wrong place. I'll have a look asap (but I'm away from my desktop the next two weeks).

**Comment by thibaudk** [comment]
Ok thanks !
No rush

**Comment by dfober** [comment]
That's fixed. The following packages are required using pkg-config:

- gl
- freetype2
- ftgl

When not found, cmake will output an error.
Note that the project generation works but on my side, the compilation fails due to an outdated implementation of GLFont.

**Comment by thibaudk** [comment]
Perfect, I'll try it now !
Cheers !
