### ISSUE TITLE
Tuplet on Chord rendering Bug

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#103]
Attempt to write the following passage from Chopin's Preludes (N°13):
<img width="351" alt="image" src="https://user-images.githubusercontent.com/3298204/69356687-28ec1b80-0c84-11ea-9391-fd1ed5ff55c5.png">

If I focus on the Tuplet, I have the following GMN that renders to something strange:
```
{[ \staff<1>  
   \clef<"g2"> \key<6> \meter<"6/4"> \stemsUp \beamsOff
   \tuplet<"-5:3-", dispNote="/4">( 
   {f#*3/20, a#*3/20 } 
   {g#*3/20, b*3/20 } 
   {f#*3/20, a#*3/20 } 
   {e#*3/20, g#*3/20 } 
   {f#*3/20, a#*3/20 })
    ]
  }
```
![image](https://user-images.githubusercontent.com/3298204/69356805-5769f680-0c84-11ea-9664-78dfa4438d35.png)

**Note** however that if I remove the chords, everything is fine... (see below). Am I missing sth or is this a bug?

```
{[ \staff<1>  
   \clef<"g2"> \key<6> \meter<"6/4"> \stemsUp \beamsOff
   \tuplet<"-5:3-", dispNote="/4">( 
   f#*3/20 
   g#*3/20 
   f#*3/20 
   e#*3/20 
   f#*3/20)
    ]
  }
``` 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/3298204/69356888-78324c00-0c84-11ea-9172-a0ab4ac4e6d2.png">

**Comment by dfober** [comment]
fixed
