### ISSUE TITLE
Incorrect beaming for nested beams

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#104]
Unit test:
```
{[  
\clef<"f4"> \key<-1> \meter<"12/8"> \stemsUp \tieBegin a-1/2. \beamBegin:1 a/8. \tieEnd \beamBegin:2 \beamBegin:3 b&/32 a/32 \beamEnd:3 g/16 a/16 \beamEnd:2 \beamEnd:1  
   \beamBegin:1 c0/8. \beamBegin:2 b&-1/16 a/16 g/16 \beamEnd:2 \beamEnd:1 
]}
```

leads to: 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/3298204/69995923-45743780-1551-11ea-8f36-28512909d20f.png">

whereas the correct rendering (according to durations) is
<img width="486" alt="image" src="https://user-images.githubusercontent.com/3298204/69995972-5cb32500-1551-11ea-9abe-28f17e423423.png">

**Note:** We had a discussion on this on Issue #58 and decided to opt for nested beaming. Examples in that ticket seem to be working (still need to pass all units).

**Comment by arshiacont** [comment]
I confirm that all unit tests related to Issue #58 pass correctly. So this seems to be a new one.

**Comment by dfober** [comment]
couldn't you simplify the writing? The following works perfectly:
~~~
[  
    \clef<"f4"> \key<-1> \meter<"12/8"> \stemsUp 
    \tieBegin a-1/2. 
    \beam ( a/8. \tieEnd b&/32 a/32 g/16 a/16)  
    \beam ( c0/8. b&-1/16 a/16 g/16 ) 
]
~~~

**Comment by arshiacont** [comment]
Hmmm we switched to `\beamBegin` and `\beamEnd` because the parser could not cope with correct ordering of paranthesis when elements are nested (text, tuplet, accidentals, fingerings etc etc) in more elaborate scores. In other words, the paranthesis closing was not being considered in the order of creation but in some implicit ordering of elements.

If you recommend using the paranthesis version I can completely switch xml2guido for this. Is there a way to see the order of parsing in Guido to adjust the ordering of construction in xml2guido as its function? I believe it is not a general problem.

**Comment by arshiacont** [comment]
@dfober Investigating moving to paranthesis beaming alltogether and passing our Unit tests.

In your correction above you removed the nested beaming in the second group. Which makes sense.

See the example below where if I don't do nested beaming the rendering is incorrect (measure 1 is correct, measure 2 is incorrect):
```
{[ 
   \clef<"g2"> \key<0> \meter<"3/8">  
   (* Correct *)  \stemsUp \beam( \beam( \tuplet<"3", dispNote="/16", position="above">( c1/24 g/24 b/24))  
   \beam( d2/16 \acc( d&/16) c/16  b1/16 )) |
 (* incorrect *)  \stemsUp \beam( \tuplet<"3", dispNote="/16", position="above">( c1/24 g/24 b/24)  
 \beam( d2/16 \acc( d&/16) c/16 b1/16 ))  
]}
```
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3298204/70038849-3de87900-15b9-11ea-9442-b37ae98990f1.png">

If I reproduce a similar example with the sample GMN above, we get this (where the nested beaming leads to incorrect rendering for the second group) - First measure is INCORRECT whereas 2nd is correct:
```
{[  
\clef<"f4"> \key<-1> \meter<"12/8"> \stemsUp 
(* Incorrect*) a-1/2. 
\beam( a/8. \beam( \beam( b&/32 a/32 ) g/16 a/16 ))  
\beam( c0/8. \beam( b&-1/16 a/16 g/16 )) 
   |
   (* Correct*)
     a-1/2. 
    \beam ( a/8. b&/32 a/32 g/16 a/16)  
    \beam ( c0/8. b&-1/16 a/16 g/16 )
]}
```
<img width="466" alt="image" src="https://user-images.githubusercontent.com/3298204/70039165-c36c2900-15b9-11ea-94ce-b4826474399c.png">

Is there any logic I am missing?

**Comment by dfober** [comment]
No, the idea was not to switch to the parenthesis version. Sorry for the confusion. The idea is to avoid nested beaming. As far as I can remember, all the examples are rendered correctly with a single beaming directive.
So for the example, you had to read:
~~~
[  
    \clef<"f4"> \key<-1> \meter<"12/8"> \stemsUp 
    \tieBegin a-1/2. 
    \beamBegin:1 a/8. \tieEnd b&/32 a/32 g/16 a/16 \beamEnd:1 
    \beamBegin:1 c0/8. b&-1/16 a/16 g/16 \beamEnd:1 
]
~~~

**Comment by arshiacont** [comment]
Thanks Dominique. Then we will have a problem with this unit test (and others in Ticket #58 -- I have more):

```
{[ 
   \clef<"g2"> \key<0> \meter<"3/8">  
   (* Correct *)  \stemsUp \beamBegin:1 \beamBegin:2 \tuplet<"3", dispNote="/16", position="above">( c1/24 g/24 b/24) \beamEnd:2  
   \beamBegin:2 d2/16 \acc( d&/16) c/16  b1/16 \beamEnd:1 \beamEnd:2 
   |
 (* incorrect *)  \stemsUp \beamBegin:1 \tuplet<"3", dispNote="/16", position="above">( c1/24 g/24 b/24)  
 \beamBegin:2 d2/16 \acc( d&/16) c/16 b1/16 \beamEnd:1 \beamEnd:2 
]}	
```

![image](https://user-images.githubusercontent.com/3298204/70055143-3c2ead80-15d9-11ea-8ff2-d1a0b249e341.png)

**Comment by dfober** [comment]
right :-(

**Comment by arshiacont** [comment]
Just out of experiment, the nested beaming actually is useful and it works! I have several unit tests from real-world classical repertoire that fits there.

It's just the one at the top which doesn't give the right duration graphically (the rest is fine).

**Comment by arshiacont** [comment]
The semantics of Guido is correct: Nested beams are used for groupings and not for graphic line indications (which is the case for example of MusicXML). 
So nesting up to 3 levels does not make any sense in MusicXML.
