### ISSUE TITLE
Chord Fingering Best Practice

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#106]
The following snippet leads to collided fingerings on top of the staff:
```
{
[
 \stemsDown \beamBegin:1 { \fingering<text="1", position="above">( e/8)
, \fingering<text="2", position="above">(g#/8), 
\fingering<text="5", position="above">(c#2/8)  } 
]
}
```

It can ofcourse be easily corrected using `dy` parameters. But I'm wondering whether there are any _plans_ for the rendering engine to correct such cases when fingerings are stacked.

![image](https://user-images.githubusercontent.com/3298204/71829124-2dd62480-30a4-11ea-815a-81bd2b7126fe.png)

**Comment by dfober** [comment]
One solution would be to write
~~~
\fingering<text="1, 2, 5"> ( { e1/8, g#, c#2 } )
~~~
i.e. apply fingering to a whole chord. The text could be stacked in description order (from bottom to top). Would that solve your problem?

**Comment by dfober** [comment]
Another solution come to my mind and that could also cover fingering change on a single note:
~~~
\fingering<text="1, 2, 5"> ( {e1/8)
~~~
similarly to the previous idea, the text could be stacked in description order. However, I have to check the reference (Gould), unless you know how fingering change on a single note should be displayed (stacked or in sequence).
Anyway, the position could be controlled using different separators e.g. ',' for stacked and ':' for sequence. What do you think ?

**Comment by dfober** [comment]
I've finally implemented the last solution (just above). Tell me if it's ok for you and if I can close this issue.

**Comment by arshiacont** [comment]
Maybe Push to Github? :)

**Comment by dfober** [comment]
Right! That's done (push).
