### ISSUE TITLE
Wrong tremolo rendered duration in prior presence of Grace

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#108]
Take the following snippet: 
```
{[ 
     \clef<"g2"> \key<2> \meter<"2/4"> \stemsUp 
   \grace( c#3/8) \stemsDown
   b2/8 a/8 a/4
  \bar 
     \trem<style="//">( {f#/2, d3/2  })
 \bar 
    \trem<style="//">( {f#2/2, d3/2  })
 ]
 }
``` 
which results to
![image](https://user-images.githubusercontent.com/3298204/72806316-3d816b80-3c55-11ea-90c4-813247d8374a.png)

Now just remove the ` \grace( c#3/8)` from the code, and you'll get correct duration for the Tremolos: 

![image](https://user-images.githubusercontent.com/3298204/72806374-5a1da380-3c55-11ea-9e89-79d45f3e6272.png)

This will happen even if the grace note is way behind Tremolos... .

**Comment by dfober** [comment]
fixed ! (and pushed :-)
