### ISSUE TITLE
Tie between chords

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#109]
How should one notate ties between notes of two chords?

Like this:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/3298204/72822852-146fd380-3c73-11ea-93d8-4e06103d57b4.png">

The following snippet (following Tie documentation online) does only one tie:
```
{[ 
   \clef<"f4"> 
    {f-1/4., c0/4., \tieBegin:1 a/4., \tieBegin:2 f1/4.  }
  { \tieEnd:1 a0/4, f1/4 \tieEnd:2  } ]
  }
```

**Comment by dfober** [comment]
you're almost there:
~~~
[ 
   \clef<"f4"> 
    {f-1/4., c0/4., \tieBegin:1<curve="down"> a/4., \tieBegin:2 f1/4.  }
  {  a0/4 \tieEnd:1, f1/4 \tieEnd:2  } 
]
~~~
Note the misplacement of **\tieEnd:1**

**Comment by arshiacont** [comment]
Ouch!!! Sorry! :)
