### ISSUE TITLE
Octava collision with upper system

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#114]
When using Octava, there is a big chance that it collides to the upper system. Example: Loading attached example in Guidoeditor can lead to the attached image.

- Is there a way to avoid this? I don't see much control over system distance in Guido by  design.
- Is there a way to include Octava (and some other similar elements such as Tempo) inside the system bounding box? (assuming that this would automatically evade collisions or maybe it's more complicated than that.

![image](https://user-images.githubusercontent.com/3298204/79789844-1b2de580-834b-11ea-9eae-6148267b9b4d.png)
[Octava.txt](https://github.com/grame-cncm/guidolib/files/4505609/Octava.txt)

**Comment by dfober** [comment]
Looks like the high position is due to the slur. But even in this case, the offset is too large.  
Actually, this issue is somehow related to #93
In the meantime, what I can try to do:
- fix the offset size
- add an option to \oct to ignore slurs when computing the offset

**Comment by arshiacont** [comment]
@dfober Thanks for your response. When I look at the original engraving the Octava is indeed high above the staff. So the offset is fine. I wouldn't bother with adding parameters and you are right that this issue is related to #93 . Give how Guido distribute Systems I am thinking that we might add some classes to the Page/System Bounding box calculation. Typically Hairpins, Tempo  and other derivations of Text would be part of that.
