### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by stubbulon5** [grame-cncm/guidolib#116]
Hello, and thank you for this amazing project.

I am having a build issue on both MacOs and Ubuntu when running :
mkdir make && cd make && cmake ../
make

31% of the way through the build I run into:

/media/zabba/EXTRA/projects/guidolib/src/engine/alt-rep/PianoRoll.cpp:33:14: fatal error: midifile.h: No such file or directory

![image](https://user-images.githubusercontent.com/42404319/81504662-7a47a000-92e2-11ea-958f-81cb23ca03fd.png)

I hope it wasn't something obvious I missed. Could you kindly shed some light?

Many thanks

**Comment by dfober** [comment]
that's likely because I've recently added a submodule and you need to run
~~~~~~~~
git submodule update --init
~~~~~~~~
otherwise, I've updated the Makefile and that's part of the `all` target now. You can as well update your repo and run `make` again.

**Comment by stubbulon5** [comment]
That worked! Thank so much. 🍻🍺
