### ISSUE TITLE
Proposal: Hidden Barline

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#117]
GuidoLib has difficulties rendering very-long measures in one system. And it is normal.

Common practice in score editing is to introduce _hidden barlines_ for very long measures so that internally they are chopped so that you have enough space on one system and allow distribution. This is very common for example in classical music cadenzas.

This proposal aims at solving this issue by allowing `\bar` tags to be hidden and to allow the rendering engine under the hood to slice them as needed. 

Take the following example as tests:
- Uncommenting `\bar` on lines 5 and 9 will make the rendering possible.

The proposal is to introduce a tag parameter on `\bar` such as `\bar<hidden="yes">`.

When a bar line is hidden:
- it will internally allow slicing
- it won't count the measure

Unit test (taken from Donizetti's _Elisir d'amore_ cadenza):
```

{[ \staff<1>  \barFormat<style= "system", range="1"> 
   (* meas. 1 *)  \clef<"g2-8"> \key<-2> \meter<"6/8", autoBarlines="off", autoMeasuresNum="system"> 
\stemsDown  g/8 b&0/8 b&/8 \stemsUp  \fermata( a/4..)  g/16 
(*\bar  ADDED BAR *)
   (* meas. 2 *)  \stemsDown \beamBegin:1 f/32 g/32 a/32 b&/32 c1/32 b&0/32 a/32 b&/32 c1/32 d/32 e&/32 d/32 c/32 d/32 e&/32 f/32 
\beamEnd:1 \text<"rall.",fattrib="i", dx=0hs, dy=18.4hs>( \beamBegin:1 a/16)
 g/16 e&/16 c/16 \beamEnd:1 
(*\bar  ADDED BAR *)

   (* meas. 3 *)  \stemsUp  \fermata( \tieBegin:1 a0/4)
 \stemsUp \beamsOff a/8 \tieEnd:1 \intens<"f", dy=17.6hs> \stemsDown \beamBegin:1 a/8 c1/8  e&/8
 \beamEnd:1 
   (* meas. 4 *)  \stemsDown \beamsOff  \fermata( \tieBegin:1 g/4)
  \beamsOff g/8 \tieEnd:1 \intens<"p", dy=17hs> \beamBegin:1  a0/8 c1/8 e&/8 \beamEnd:1 
   (* meas. 5 *)  \beamsOff  \fermata( \tieBegin:1 \acc( g&/4) )
  g&/8 \tieEnd:1 \beamsOff \fermata( \tieBegin:1 f/4)
   f/8 \tieEnd:1 \bar 
   (* meas. 6 *)  \text<"a tempo",fattrib="i", dx=0hs, dy=15.2hs>(  b&0/8)
 _/8 _/8 _/4. ]
  }
```

**Comment by dfober** [comment]
ok for me, seems a reasonable solution. 
I guess you know there is a \newSystem tag but it enforces a line break while an invisible bar still let the engine decide.

**Comment by arshiacont** [comment]
Another argument for adding the "hidden" parameter is to conform to most existing engravings (for example, when incoming from MusicXML). Engravers seem to have the habit of hiding barlines in such cases.

**Comment by dfober** [comment]
that's done and pushed. The implementation is as suggested: a hidden tag parameter.

**Comment by arshiacont** [comment]
@dfober Just compiled and tried.. I can see the ARBar propagation to GRBar and the `return` in the draw method when hidden. But they are drawn anyway!!! :) Any idea?

```
{[ \staff<1>  \barFormat<style= "system", range="1"> 
   (* meas. 1 *)  \clef<"g2-8"> \key<-2> \meter<"6/8", autoBarlines="off", autoMeasuresNum="system"> 
\stemsDown  g/8 b&0/8 b&/8 \stemsUp  \fermata( a/4..)  g/16 
\bar<hidden="true">

   (* meas. 2 *)  \stemsDown \beamBegin:1 
f/32 g/32 a/32 b&/32 c1/32 b&0/32 a/32 b&/32 c1/32 d/32 e&/32 d/32 c/32 d/32 e&/32 f/32 
\beamEnd:1 \text<"rall.",fattrib="i", dx=0hs, dy=18.4hs>( \beamBegin:1 a/16)
 g/16 e&/16 c/16 \beamEnd:1 
\bar<hidden="true">

   (* meas. 3 *)  \stemsUp  \fermata( \tieBegin:1 a0/4)
 \stemsUp \beamsOff a/8 \tieEnd:1 \intens<"f", dy=17.6hs> \stemsDown \beamBegin:1 a/8 c1/8  e&/8 \beamEnd:1 
\bar<hidden="true">

   (* meas. 4 *)  \stemsDown \beamsOff  \fermata( \tieBegin:1 g/4)
  \beamsOff g/8 \tieEnd:1 \intens<"p", dy=17hs> \beamBegin:1  a0/8 c1/8 e&/8 \beamEnd:1 
\bar<hidden="true">

   (* meas. 5 *)  \beamsOff  \fermata( \tieBegin:1 \acc( g&/4) )
  g&/8 \tieEnd:1 \beamsOff \fermata( \tieBegin:1 f/4)
   f/8 \tieEnd:1 
\bar 
   (* meas. 6 *)  \text<"a tempo",fattrib="i", dx=0hs, dy=15.2hs>(  b&0/8)
 _/8 _/8 _/4. ]
  }
```

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3298204/82474245-0fa91800-9acb-11ea-83c1-ec48900d51b9.png">

**Comment by dfober** [comment]
Sorry, there was a missing initialization in one GRBar constructor (which was not used with my tests).
That's fixed and pushed.

**Comment by arshiacont** [comment]
Thank you! Works like a charm
