### ISSUE TITLE
Proposal: Ability to reset/set measure number on Bar tag

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#118]
Currently the measure number is internally calculated in GuidoLib. We can control how measure numbers appear with Barformat's `style` parameter and whether they appear or not with Bar tag's `displayMeasNum` parameter. 

The proposal is to introduce a tag parameter on _bar_ tag such as `measNum=<int>` whose role is to _reset the internal measure number to parameter value._

I can see several benefits to this:
- _Pickup Measure_ numbering which is currently incorrect in GuidoLib and it would be best to leave it to the engraver discretion (we will break other behavior if we try to do this automatically!).
- In situations where we want to show _excerpts_ of a score with correct measure numbring.
- In situations where one doesn't want to use explicit bar tag but would want to affect numbering (many contemporary music examples).

**Comment by dfober** [comment]
agree ! I'll do it asap.

**Comment by dfober** [comment]
That's done. Tell me if it's ok for your.

**Comment by dfober** [comment]
can I close this issue ?

**Comment by arshiacont** [comment]
Yes looks fine.. I'll create another ticket if I see anything strange.. sorry for the delay
