### ISSUE TITLE
BUILD FAILED when 'make ios'

### ISSUE THREAD

**Issue by SaqG** [grame-cncm/guidolib#119]
In file included from /Users/saq/Desktop/guidolib-dev/src/engine/alt-rep/PianoRollTrajectory.cpp:23:
In file included from /Users/saq/Desktop/guidolib-dev/build/../src/engine/alt-rep/PianoRollTrajectory.h:17:
/Users/saq/Desktop/guidolib-dev/build/../src/engine/alt-rep/PianoRoll.h:29:10: fatal error: 
      'MidiShareLight.h' file not found
#include "MidiShareLight.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC iosdir/guidolib.build/Release-iphoneos/GUIDOEngine.build/Objects-normal/arm64/PianoRollTrajectory.o /Users/saq/Desktop/guidolib-dev/src/engine/alt-rep/PianoRollTrajectory.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [ios] Error 65

**Comment by dfober** [comment]
That's due to a recent submodule. You should update your submodules:
~~~~~~
$ git submodule update --init
~~~~~~
that was automatic with the `all` target, I've added the update to the `ios` target too. Thus you can update your repo and relaunch the `make ios` as well.

**Comment by SaqG** [comment]
yes,thanks a lot, it build success.I just drag libguidoengine.a into my project, right? Is there anything else?

**Comment by SaqG** [comment]
Can you help me integrate it into my IOS project? Thank you

**Comment by dfober** [comment]
I'm really not an expert in iOS dev. I'm afraid I can't help you.
