### ISSUE TITLE
Support for Multimeasure Rests

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#120]
Probably the only citizen missing in the language to make it world-class: Multimeasure Rest

Looking at the Language Specification it doesn't look very obvious! Maybe this can be done through the `restFormat` tag? or just when the rest duration is huge accompanied by a restFormat indicating that it should be rendered as a multi-measure rest?

https://en.wikipedia.org/wiki/Rest_(music)#Multiple_measure_rests

**Comment by dfober** [comment]
I'll have a look at it. A new tag could be introduced for that (e.g. \mrest for multi-measure rest or something similar).

**Comment by dfober** [comment]
That's done ! You can update your repo. You'll find an example in `gmn-examples/new-tags-v1.69/multiMeasuresRest.gmn`
