### ISSUE TITLE
Compiling errors when compiling GUIDOEngine target

### ISSUE THREAD

**Issue by jjceresa** [grame-cncm/guidolib#121]
Hello Dominique,

I got a bunch of the same compiler error when compiling GUIDOEngine target, like this:

1>------ Début de la génération : Projet : GUIDOEngine, Configuration : Debug Win32 ------
1>La génération a démarré 16/12/2020 00:27:16.
1>InitializeBuildStatus:
1>  Mise à jour de l'horodatage "GUIDOEngine.dir\Debug\GUIDOEngine.unsuccessfulbuild".
1>CustomBuild:
1>  Toutes les sorties sont à jour.
1>ClCompile:
1>  ARAccelerando.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARFontAble.h(38): error C2864: 'ARFontAble::fFontSize' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\TempoChange.h(40): error C2864: 'TempoChange::fDx2' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARAccidental.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARAccolade.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARAlter.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARArpeggio.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARArticulation.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARAuto.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARAuto.h(122): error C2864: 'ARAuto::fHasFingeringPos' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARAuto.h(123): error C2864: 'ARAuto::fHasHarmonyPos' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARAuto.h(124): error C2864: 'ARAuto::fHasFingeringSize' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARBar.cpp
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARMusicalObject.h(110): error C2864: 'ARMusicalObject::fDrawGR' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>d:\winprojet\git\github\guidolib-dev\src\engine\abstract\ARBar.h(96): error C2864: 'ARBar::fHidden' : seules les données membres static const intégrales peuvent être initialisées dans une classe
1>  ARBarFormat.cpp
La génération a été annulée.

I think that all those default variable's value should be initialized in the respective constructor rather than in the object class definition file (.h).
There are a lot of these variables and fixing that will take time. I propose to do the fix in a branch that I could upload as it seems to be the easiest way. Opinions ?
Regards

**Comment by dfober** [comment]
Class members can be initialized in class definition since C++11, which is required to compile the library. Can I get more information about the compiler, the platform you're using?

**Comment by jjceresa** [comment]
>Can I get more information about the compiler, the platform you're using?

I am using Visual Studio 10 and it seems that the compiler isn't C++11 compliant. But VS10 compiler complains only on this error. Also, other Guido tools compile successfully. Another issue is that I am running on Windows XP on which recent Visual Studio fails to install :(.
Please, could you tell me more about reason of C++11 requirement for this library?.

**Comment by dfober** [comment]
I'm afraid Visual Studio 10 is too old. One solution is to initialize the field in the constructor but it's likely that you'll get some more errors next. The library relies on C++11 with many other parts. You could use the [binary distribution](https://github.com/grame-cncm/libmusicxml/releases/tag/v3.18) but it's also likely that you'll get another issue with the runtime dependencies.

**Comment by jjceresa** [comment]
>...You could use the binary distribution ... 

Thanks, I wasn't aware of the binary existence.

>..but it's also likely that you'll get another issue with the runtime dependencies.

Yes, I feel that this leads toward a lot of complication. Anyway, many thanks Dominique for your reactive answer and useful information. All the best to you and the scientist team (SL, YO).
Please feel to close this issue at any time.
