### ISSUE TITLE
map/set iterators incompatible exception

### ISSUE THREAD

**Issue by WindowsNT** [grame-cncm/guidolib#123]
When calling 

bool TagParameterMap::checkExist (const TagParameterMap& list) const

Call stack from GuidoString2AR with a non-empty guido string.

Occurs only in debug builds as this is where the iterator debugging occurs.
VS 2019, x64 debug build.

**Comment by dfober** [comment]
It might be due to the fact that it includes non-debug libraries (whatever the config is debug or release).
I never tried to compile with VS 2019 too. That might be also a reason.
Do you have more information about the exception ?

**Comment by WindowsNT** [comment]
Line 113 

`		if (list.find(i->first) == end()) {
`
should be

`		if (list.find(i->first) == list.end()) {`

**Comment by dfober** [comment]
fixed and pushed to git (dev branch)
tell me if that solves the problem
