### ISSUE TITLE
Clef hit test?

### ISSUE THREAD

**Issue by WindowsNT** [grame-cncm/guidolib#128]
On Graph2TimeMap call I know the position of the elements, but clefs are not included.
It would be nice to have a GuidoElementType::kClef.

**Comment by dfober** [comment]
That's done, could you check ? 
By the way, I've also added an access to the \meter map.
Note that you have to use the corresponding `GuidoElementSelector`

**Comment by WindowsNT** [comment]
Very good. +1.
