### ISSUE TITLE
The help line has offset problems in some cases

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/guidolib#135]
These are the two scores I tested. I tried to find the problem, but I haven't broken through..
[test.zip](https://github.com/grame-cncm/guidolib/files/7611471/test.zip)
![image](https://user-images.githubusercontent.com/27411051/143674673-6a761a24-93b9-4156-ae76-90d2b230dc88.png)
![image](https://user-images.githubusercontent.com/27411051/143674684-53d72722-016c-4fb1-b1a7-b24258c5dad6.png)
![image](https://user-images.githubusercontent.com/27411051/143674746-acb6e81f-05a6-42b7-b7dc-8cc6c02f09af.png)

**Comment by zhwei8090** [comment]
The guido library is adapted according to which notation software, because I found that the effects presented by different software are a little different

**Comment by arshiacont** [comment]
@zhwei8090 Guido Library is dependent by itself and is a renderer of the Guido Language. If you are talking about LibMusicXML, then the answer is Finale XML Export.

I believe in your case, it is best to submit the GUIDO score for debugging. If you believe the problem is on LibMusicXML then create a ticket on the corresponding GitHub.

**Comment by arshiacont** [comment]
I just looked at test1 and it looks like a rendering issue (rendered on GuidoEditor online):


```
{[ \staff<1> \title<"太 空 漫 步"> \auto<autoInstrPos="on"> \instr<"钢琴"> \accol<id=0, range="1-2"> \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"g2"> \key<-1> \meter<"4/4", autoBarlines="off", autoMeasuresNum="system"> \tempo<"Eerily   神秘地",fattrib="b", dy=0hs, dx=-27.736> \intens<"mf", dy=0hs> _/2 _/4 \stemsUp \beamsOff \fingering<position="above", text="1">( f1/4)
 \bar<measNum=2> 
   (* meas. 2 *)  \stemsUp \beamsOff a1/2 \stemsUp \beamsOff f1/4 _/4 \bar<measNum=3> 
   (* meas. 3 *)  \stemsUp \slurBegin:1<curve="up"> \beamsOff \fingering<position="above", text="2">( \acc( g&1/2)
)
 \stemsUp \beamsOff \acc( a&1/4)
 \stemsDown \beamsOff b&1/4 \bar<measNum=4> 
   (* meas. 4 *)  \stemsUp \beamsOff \acc( g&1/2.)
 \slurEnd:1 _/4  ]
 , 
[ \staff<2>\barFormat<style= "system", range="2"> 
   (* meas. 1 *)  \staffFormat<distance=13> \clef<"f4"> \key<-1> \meter<"4/4", autoBarlines="off", autoMeasuresNum="system"> \stemsDown \beamsOff \fingering<position="below", text="5">( f0/4)
 \stemsDown \beamsOff a0/4 \stemsDown \beamsOff c1/4 _/4 \bar<measNum=2> 
   (* meas. 2 *)  _/1 \bar<measNum=3> 
   (* meas. 3 *)  \stemsAuto \beamsOff {\tieBegin:1 \fingering<position="below", text="1">( \fingering<position="below", text="2">( b&0/1)
)
, \tieBegin:2 c1/1  } \bar<measNum=4> 
   (* meas. 4 *)  \stemsDown \beamsOff {b&0/2. \tieEnd:1, c1/2. \tieEnd:2  } _/4  ]
  }
```


![image](https://user-images.githubusercontent.com/3298204/143677691-b471d697-6c88-41af-9064-46e50e443852.png)

**Comment by zhwei8090** [comment]
@arshiacont Yes, I think there is a problem with the offset calculated in the OnDraw method of GRSingleNote, but I still don’t know how to change it.

**Comment by dfober** [comment]
fixed (available from dev branch)

**Comment by zhwei8090** [comment]
@dfober thank you very much
