### ISSUE TITLE
Cross-Staff Beaming Rendering Issue

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#137]
I believe this issue was already addressed previously! We might be in a special case here (such as number of Beams?!) which was not covered previously:

```
{[ \staff<1> \accol<id=0, range="1-2"> \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"g2"> \key<-5> \meter<"C"> 
   \stemsDown \beamBegin:1 \beamBegin:2 f2/32 e&2/32 c2/32 b&1/32 \beamEnd:2 \beamBegin:2 
   \staff<2> \stemsUp g&1/32 e&1/32 c1/32 b&0/32 \beamEnd:1 \beamEnd:2 
   \staff<1> \stemsDown \beamBegin:1 \beamBegin:2 c2/32 b&1/32 g&1/32 f1/32 \beamEnd:2 \beamBegin:2 
   \staff<2> \stemsUp e&1/32 c1/32 b&0/32 g&0/32 \beamEnd:1 \beamEnd:2 \staff<1> _/2 ]
 , 
[ \staff<2>
   (* meas. 1 *)  \clef<"f4"> \key<-5> \meter<"C"> _/1 ]
  }
```

Leads to: 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/3298204/145095224-d1fbad6a-1c7d-4094-8b03-f389325d1bfc.png">

Expected:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/3298204/145095267-760b7cc5-be69-4a0b-91b4-13495bdf5f3c.png">

**Comment by dfober** [comment]
fixed
