### ISSUE TITLE
This type of continuous line is not supported?

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/guidolib#142]
![image](https://user-images.githubusercontent.com/27411051/156749309-f5ae3a96-efb9-4fb3-b2b7-52925a3a3236.png)
this is the attachment ： [x_test.xml.zip](https://github.com/grame-cncm/guidolib/files/8185196/x_test.xml.zip)

![image](https://user-images.githubusercontent.com/27411051/156749585-56fce524-db1f-4121-b1bd-9ba5df9fdf1e.png)

**Comment by arshiacont** [comment]
as of this writing, Slurs between different voices are not allowed in GuidoLib. You confirm @dfober ? 
in the latest xml2guido, they are simply ignored.

Your example might be written in a Guido syntax where everything is on one voice which should probably solve the issue but it depends on how it is notated in the MusicXML (which in your case, is using two layers);

**Comment by dfober** [comment]
yes I confirm: slurs between different voices is poorly supported. 
You have to express the slur inside the same guido voice e.g. [ \staff<1> e \slur(d \staff<2> g2) ]

**Comment by zhwei8090** [comment]
@arshiacont @dfober  Understood, thank you
