### ISSUE TITLE
"none" Accidental introduces extra Offset in Chords

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#145]
Normale behavior without a chord:
```
{[ \staff<1> \clef<"g2"> \stemsUp \acc( a#1/16) ], 
[ \staff<1>  \stemsDown  \acc<"none">( a#1/16) ]}
```
leading to: 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/3298204/158793168-d9c9bc0e-997c-4e0a-8376-d7adcf956ee3.png">

Same but in a chord, where the renderer adds an _extra space_ between the note and the accidental. It actually becomes nasty on a real score:

```
{[ \staff<1> \clef<"g2"> \stemsUp {\acc( a#1/16),  e2/16}  ], 
[ \staff<1>  \stemsDown  \acc<"none">( a#1/16) ]}
```

<img width="264" alt="image" src="https://user-images.githubusercontent.com/3298204/158793402-532bf1b3-29de-4f73-ac77-b595937bb2ff.png">

**Comment by arshiacont** [comment]
After testing: the real issue here is that a `\acc<"none">` tag introduces an extra dx space where it should be treated as _invisible_ of some sort. @dfober

**Comment by dfober** [comment]
fixed
