### ISSUE TITLE
Beam Height becomes zero if Empty is present in sequence

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#146]
Unit test:

```
{[ \beamBegin:1 d1/8 empty/8  d1/8 empty/8  d1/8 empty/8  d1/8 \beamEnd:1]}
```

<img width="430" alt="image" src="https://user-images.githubusercontent.com/3298204/158797417-6626180b-6d10-46de-bc0f-49feea5cc5f1.png">

**Comment by dfober** [comment]
fixed
