### ISSUE TITLE
How i build midi2guido to bin file

### ISSUE THREAD

**Issue by motniemtin** [grame-cncm/guidolib#149]
How i build midi2guido to bin file ?

**Comment by dfober** [comment]
midi2guido is not supported any more, it depends on an external library that is not part of the guido repository.

**Comment by clyde-gustafson** [comment]
By chance, would you happen to know what that library is? I'd like to convert a midi to gmn, and I can re-import into a fork if needed.

**Comment by dfober** [comment]
The midi2guido library is a very old binary. The source code is not available and thus cannot be re-build. To convert from midi to gmn, I suggest to use the musicxml format as intermediate format. A converter from musicxml to guido is available from [libmusicxml](https://github.com/grame-cncm/libmusicxml).
