### ISSUE TITLE
[Feature Request] support for \autoMeasureNum="line"

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#15]
Currently the `\autoMeasureNum` tag accepts the `"page"` parameter, inserting automatically measure numbers on the first measure of each new page.

It would be really great (and coherent with many score editions) to extend this feature for `"line"` to automatically insert measure number on each new line/system/line-break generated by Guido.

**Comment by cdecron** [comment]
I guess this issue should be closed since it has been implemented.

**Comment by dfober** [comment]
done

**Comment by arshiacont** [comment]
Thanks!
