### ISSUE TITLE
staccato and tenuto

### ISSUE THREAD

**Issue by Jaimyy** [grame-cncm/guidolib#151]
I cannot use both staccato and tenuto on more than one note at the same time.

```
{[ \clef<"g2"> \key<0>

g2/8 _/8
\stacc(\ten(g2/8)) _/8
\stacc(\marcato(g2/8)) _/8
\stacc(\accent(g2/8)) _/8
\stacc(\mord(g2/8)) _/8\bar

{e2/8, g2/8} _/8
\stacc(\ten({e2/8, g2/8})) _/8
\stacc(\marcato({e2/8, g2/8})) _/8
\stacc(\accent({e2/8, g2/8})) _/8
\stacc(\mord({e2/8, g2/8})) _/8\bar]}
```

![grafik](https://user-images.githubusercontent.com/103506613/163414194-372d3fe8-8075-4f48-81f3-0d3b049e6b27.png)

**Comment by zhwei8090** [comment]
Indeed multiple tags are not supported

**Comment by dfober** [comment]
It should! I've started to look at the problem but it's not trivial. It' s going to take a little patience...

**Comment by dfober** [comment]
fixed (on dev branch)
