### ISSUE TITLE
Repeat markers for end and start are not supported

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/guidolib#153]
![image](https://user-images.githubusercontent.com/27411051/166093804-fb043f78-76b6-44dc-a7fd-799cc8c34b26.png)
It's like this on the sheet music software：
![image](https://user-images.githubusercontent.com/27411051/166093840-a2b951f1-99df-4e16-be00-6effef396981.png)
By checking, I found that there is no such mark symbol in the font file, but I don't know how to increase the font symbol

Here is my test file：[test3.xml.zip](https://github.com/grame-cncm/guidolib/files/8596246/test3.xml.zip)

**Comment by dfober** [comment]
this is because  \bar are inserted between \repeatEnd and \repeatBegin. Although hidden, they take space. Just remove them and you'll get a correct rendering.

**Comment by zhwei8090** [comment]
This is indeed the case, I am thinking how to solve it from the code level, because the xml exported from finale is like this

**Comment by arshiacont** [comment]
@zhwei8090 Feel free to fix this behavior on `xml2guido`. I have never bothered with Repeat tags and there is definitely room for improvement there.

**Comment by zhwei8090** [comment]
This problem has been solved, but it has been fixed in libmusicxml, and pr has been submitted to see if it is reasonable
