### ISSUE TITLE
This label is not supported (inverted turn), can you add a font like this?

### ISSUE THREAD

**Issue by zhwei8090** [grame-cncm/guidolib#157]
Our font library does not have this symbol, can you support it?
![image](https://user-images.githubusercontent.com/27411051/174041469-2bb0c0cf-d9ca-4d1e-8e7c-33480c3649b7.png)

**Comment by zhwei8090** [comment]
@dfober  Can a font like this be added? Our textbook is like this

**Comment by dfober** [comment]
Yes, I'll have a look. I'm really not an expert in font design (are you?) but I'll try to add it.

**Comment by zhwei8090** [comment]
I don't have the original file here, otherwise we can design and add it (if you have it, can you send me a copy of the original font file, thank you very much)

**Comment by dfober** [comment]
The guido font file is part of the src code and is available on [github](https://github.com/grame-cncm/guidolib/blob/dev/src/guido2.ttf).

**Comment by zhwei8090** [comment]
Hahaha, this is different from what I understand, I want to know the original file for making ttf, such as ps and the like

**Comment by zhwei8090** [comment]
ok,thank you very much

**Comment by zhwei8090** [comment]
It's really not easy to add this, it's been an hour and I haven't succeeded

**Comment by dfober** [comment]
That's done. Note that \turn has now a new type: `invertedb` that you should use for the new glyph.
See the [guido doc](https://guidodoc.grame.fr/refs/tags/Ornaments/#turn)
Can you check and close this issue if that's fine.

**Comment by dfober** [comment]
could you post a picture of what happens?

**Comment by arshiacont** [comment]
The first two measures of Suite Bergamesque by Debussy!! 😜 (coloring is mine)
![image](https://user-images.githubusercontent.com/3298204/176746759-763e5327-3683-4c1e-ba72-fd6ad74acf4c.png)

**Comment by arshiacont** [comment]
i do.. also in the simulator (thus OSX)

**Comment by arshiacont** [comment]
If I just use the old font with the new engine everything is fine (but there will be a missing symbol at some point I guess)

**Comment by dfober** [comment]
I'll send you another version (by email).

**Comment by arshiacont** [comment]
The font version you sent by email works fine and has corrected the issue.

**Comment by dfober** [comment]
Ok, I'll update the repository as soon as possible.

**Comment by dfober** [comment]
The font has been updated and pushed to github. Can you check?

**Comment by zhwei8090** [comment]
@dfober  Verified, no problem
