### ISSUE TITLE
Correctly show embellishments for Great Highland Bagpipes

### ISSUE THREAD

**Issue by tomvodi** [grame-cncm/guidolib#163]
The Great Highland Bagpipe is verry unique in its variety of embellishments, which consists of multiple grace notes beamed together by up-stems. See http://www.potomacvalleyscottishfiddle.org/public/the_pipers_corner/ for most of the used embellishments.

I tried out the Guido lib editor to accomplish an embellishment called grip as an example but failed with that.

At first I tried the code:
`\stemsUp  \beam(\grace(g/32 d2 g1))` but this results in a middle note which is half covered in the stems of the surrounding grace notes.

My next try was to lengthen the stems to 10:
`\stemsUp< length=10.0>  \beam(\grace(g/32 d2 g1))` which results in the middle stem to poke through the beams.

Can this be fixed somehow? Or maybe I'm missing something here.

**Comment by tomvodi** [comment]
Hi Dominique, thank you for your fast response. Glad to hear you're working on it!

**Comment by dfober** [comment]
That's fixed and pushed to dev branch. Tell me how it works with all of your ornaments.

**Comment by tomvodi** [comment]
Hi Dominique, I haven't found any problems in the new version. Thank you.
The only thing that doesn't look that nice are the beams for embellishments, where the first note is quite high and the last is verry low. There, the beam is verry steep. E.g. a thumb shake movement: `\stemsUp< length=7.0> \beam(\grace(a2/32 d2 g1))` 
![thumb-shake](https://user-images.githubusercontent.com/883361/200111905-85f5da99-45c9-4e82-8079-0da14bc98e71.png)

But you don't need to fix that, as I'm currently only researching for libraries that are suitable for some kind of interactive notation program for the great highland bagpipes.

**Comment by dfober** [comment]
this is due to the enforced stems length, just remove the `<length=7.0>` and it'll look nicer
