### ISSUE TITLE
lower part with half note 

### ISSUE THREAD

**Issue by guandi156** [grame-cncm/guidolib#164]
Hello, The lower part is a half note, but coincides with the upper part. This shows only quarter notes. How can I make the lower part become half notes?

![33333](https://user-images.githubusercontent.com/105865035/200584474-3f41fdfc-12f7-432e-b48d-ca35b4dad3f5.png)

This shows only quarter notes. How can I make the lower part become half notes?
Thank you! 

![2222](https://user-images.githubusercontent.com/105865035/200584506-facc91b2-9251-4435-b9c2-1192e96b010a.png)

**Comment by dfober** [comment]
There is a workaround: don't draw the notehead e.g.:
~~~~~~~~
{
[
	\meter<"4/4"> 
	\stemsUp \beam(c1/8 e g c2)
	% workaround : using notehead style
	\stemsUp \beam(\noteFormat<style="none">(c1/8) e g c2)
]
, [
	\staff<1> 
	\stemsDown c/2
	\stemsDown c/2
]
}
~~~~~~~~
but it is not the ideal solution. In fact that should be automatic. I'll look into it.

**Comment by guandi156** [comment]
It works with \noteFormat<style="none"> Thank you very much!

**Comment by dfober** [comment]
fixed. There is now an automatic detection of this kind of issue that is solved by hiding the note head.
