### ISSUE TITLE
Grace rending conflict with noteFormat

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#17]
using `\grace` tag creates conflict when used _before_ or _after_ a note/chord containing `\noteFormat`. 

Use this [reduced sample](https://github.com/grame-cncm/guidolib/files/975953/graceNoteFormatBug_gmn.txt). It has three staves:

- **Staff 1:** A `\grace` in the middle of two chords with `\noteFormat`. Rendering is blocked.
- **Staff 2:** Same thing with `\grace` removed. Rendering is not blocked.
- **Staff 3:** same as _Staff 1_ but with `\noteFormat` removed inside the grace chord. Note that the regular grace chord is _not_ rendered correctly. If you remove the `\noteFormat` from the prior chord then it'll be fine. Seems like the presence of `\noteFormat` somehow messes up the sequence for `\grace`.

**Comment by dfober** [comment]
I see... It looks like the \noteFormat tag is seriously disturbing the rendering, even on staff 3 (the grace size is incorrect and becomes correct when you remove the preceding \noteFormat).
I'll have a look asap...

**Comment by arshiacont** [comment]
no rush on this one.. if I could upvote, it'd be Issue #15 :)

**Comment by arshiacont** [comment]
Just head running on this issue, since `\mordent` and `\trill` issues with `\noteFormat` are now resolved since 1.6.5

**Comment by dfober** [comment]
fixed (although similar issues should remain e.g. with restFormat, I didn't got time to design a more general solution)
