### ISSUE TITLE
Incorrect beam dash direction

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#171]
Can't figure out the pattern producing the bug. But here is a unit test:
```
{[ \clef<"g2"> \key<-1> \meter<"6/8">
   \beamBegin:1  f2/8.. e2/32 d2/16. c2/32 \beamEnd:1 
   \beamBegin:1  b1/8.. a2/32 g2/16. b1/32 \beamEnd:1 ]}
```
leading to:
![image](https://github.com/grame-cncm/guidolib/assets/3298204/8a3d43f0-d3c1-449d-8ad8-7e7040a3117e)
whereas the correct rendering should look like: 
<img width="493" alt="image" src="https://github.com/grame-cncm/guidolib/assets/3298204/c1e32edf-2ed0-4743-93eb-33674434e841">

(For my internal use: PK3249)

**Comment by dfober** [comment]
fixed (on branch dev)
