### ISSUE TITLE
Cross Staff Grace Notes rendering issue with Beaming

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#173]
Two issues with the following excerpt:
1. the crossed staff grace beaming is incorrect
2. this excerpt will lead to a crash on the Destructor of `GRGrace` class if the corresponding instance of `GRHandler` is freed.

```
{[ \staff<1>  \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"g2"> \key<-1> \meter<"C/"> 
   \stemsUp f#1/2  a1/4 \stemsDown  d#2/4 \bar<measNum=2> 
   (* meas. 2 *)  f#2/2. _/4 
 ]
 , 
[ \staff<2> 
   (* meas. 1 *)  \clef<"f4"> \key<-1> \meter<"C/"> \stemsUp \grace( \beamBegin:1  b#-2/16 d#-1/16 f#-1/16 a-1/16  b#-1/16 d#0/16 f#0/16
 \beamEnd:1 \staff<1> \stemsDown \beamBegin:1 a0/16 b#0/16 d#1/16 
 \beamEnd:1)
 empty/1 \staff<2>  
   (* meas. 2 *)  \fermata( _/1)
]}
``` 

Currently rendered as 
![image](https://github.com/grame-cncm/guidolib/assets/3298204/96e34bc3-5308-4163-b645-2b03572da453)

Expected similar to:
<img width="484" alt="image" src="https://github.com/grame-cncm/guidolib/assets/3298204/5f556e11-aca1-4513-b8a2-50b7c65cae7f">

**Comment by dfober** [comment]
the crash bug is solved, but not yet the beaming issue

**Comment by arshiacont** [comment]
Thanks @dfober ! That's already much better

**Comment by dfober** [comment]
fixed
