### ISSUE TITLE
Could you please consider using exact version strings as tags?

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#179]
It isn't clear from ```177``` whether this stands for the version ```177```, ```1.77```, or ```1.7.7```.

Here is how the FreeBSD's automatic new version discovery system shows guidolib:
![image](https://github.com/grame-cncm/guidolib/assets/271906/2e5265d4-ece8-4a01-9122-24d3a25c1f3c)

It always prompts that ```NNN``` (which is currently 177) is the latest version, and we need it to show the real version with dots.
Virtually all projects are tagged with the real version. But guidolib (and inscore too) stand out, making it impossible to know when the new version is released.

I am sure that almost all other distros have the same problem.

Thank you,
Yuri

**Comment by dfober** [comment]
if I rename the tag, is that OK?

**Comment by yurivict** [comment]
> if I rename the tag, is that OK?

Yes.

**Comment by dfober** [comment]
That's done

**Comment by yurivict** [comment]
Thanks!
