### ISSUE TITLE
Unwanted rendered space for mid-measure \clef

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#18]
This used to be [Bug #23 on the old SourceForce](https://sourceforge.net/p/guidolib/bugs/23/) but it has come back probably in a different form.

The Clef change in Measure 2 of this score generates unwanted space: 

```
{ 
[ \staff<1>  \accol<id=0, range="1-2"> \barFormat<style= "system", range="2-3"> 
   (* meas. 1 *)  \beamsOff f/8  \stemsUp  a&1/4 \intens<"p", dy=-3hs>  g/8 \bar 
   (* meas. 2 *)  \stemsUp \beam( c1/8 e/8 a&/8  f/8) \bar 
 ]

, [ \staff<2>  (* 1st voice *)
   (* meas. 1 *)   \beamsOff  { f-2/8, f-1/8 } _/8 _/4 \bar 
   (* meas. 2 *)   _/8 \clef<"g2"> _/8 _/4 \bar 
 ]
, [ \staff<2> (* 2nd voice *)
   (* meas. 1 *)  empty/2 \bar 
   (* meas. 2 *)  empty/2 \bar 
  ]
 }
```

Two manual ways to get rid of this space after trial and error are:

1. remove the `\beamsOff` in measure 1 of 1st voice of staff 2; or
2. remove the 2nd voice of staff 2 entirely

I tried to reduce the complex score as much as I could to make it meaningful! :)

**Comment by dfober** [comment]
Ok, I've got it!
This is actually not an issue: the engine forbids a clef insertion on the duration of a note.
`empty` has the same status than notes, one could replace the last empty with a note (e.g. c0/2) to make that visible. Using `empty/8 empty/4` instead `empty/2` solves the problem.
