### ISSUE TITLE
No Bar Request

### ISSUE THREAD

**Issue by WindowsNT** [grame-cncm/guidolib#184]
Would be useful to me if even the ending of the score would use a plain line bar.
Like \barFormat<"system", range="None">   or something like that.

**Comment by dfober** [comment]
Just put a regular barline at the end  e.g.
~~~~~~~~~~~~
[
	a b c |
]
~~~~~~~~~~~~
Does that answer your question?

**Comment by WindowsNT** [comment]
Super, thanks.
The idea is that, since I can't force guido to put a fixed number of measures in my page, I can draw a subsection of the score myself (i.e. different gmn file) so there is no 'end'.

**Comment by dfober** [comment]
Note that you can force a fixed number of measures by line by inserting a \newline tag, or by page with \newPage.
The result may be shaky thus it's recommended to do that manually.
