### ISSUE TITLE
Automatic measure numbering

### ISSUE THREAD

**Issue by PhilippeCuvillier** [grame-cncm/guidolib#21]
It would be very interesting (both for score users and for debugging issues) that Guido automatically draws measure numbers at the beginning of each system, like in the following screenshot.
<img width="562" alt="capture d ecran 2017-05-22 a 15 20 35" src="https://cloud.githubusercontent.com/assets/28864881/26311295/1e5d95c2-3f04-11e7-8621-33c3e1ab75be.png">

1. _First step:_ implement the basic mechanism. Increment a measure counter at each new measure, and displays number after each line break.

2. _Second step:_ handle "implicit" MusicXML attribute. Pickup measures (anacrouses) might appear at the beginning of the score but also in the middle of some scores. The convention is that a pickup measure does not count in the numbering. So if the score begins with a pickup, this measure does not display its number, and by convention its hidden number is 0 (so that the first "real" measure has number 1). See the following screenshot for an example.
<img width="363" alt="capture d ecran 2017-05-22 a 15 33 20" src="https://cloud.githubusercontent.com/assets/28864881/26311321/363fae6e-3f04-11e7-9e0a-c3b27fab0e37.png">

To implement this, it suffices to mimic MusicXML, which handles the case with a measure attribute called "implicit" (see MusicXML [documentation](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-measure.htm))
So it would be great to implement such an "implicit" attribute in Guido, and take into account with the automatic numbering by "ignoring" implicit measures (i.e. not incrementing counter).

**Comment by dfober** [comment]
that's done

**Comment by cdecron** [comment]
Actually, the second point (about some kind of "implicit" bar param) has not been done yet. I guess this issue should be split.

**Comment by dfober** [comment]
Right ! I think the second point needs to be discussed. 
To me, an `implicit` attribute is not very clear from a semantic point of view, in fact the underlying calculation is the increment of the measurement number, why not call it `increment`. The other pb is also the multiplication of the attributes: `displayMeasNum` could also take the value 'skip' which could be both an equivalent of 'false' + no increment. Finally, a `num` attribute could be also considered, making a reset of the measure number to a specified value. It would also make it possible to segment the partitions into several files while maintaining the consistency of the measure numbers.

**Comment by cdecron** [comment]
I talked with Philippe about this, and for him the `displayMeasNum` param with `skip` value, and the `num` attributes are two features quite different which are both useful, but the second one shouldn't replace the first one.

**Comment by dfober** [comment]
I agree.
