### ISSUE TITLE
Font size change for tempo indication

### ISSUE THREAD

**Issue by iv41879** [grame-cncm/guidolib#23]
Dear @dfober , I cannot change the font size of the tempo marking. Am I doing something wrong or it is a bug? So in this particular attached sample test file I would like that my tempo indication is with equal font as instrument name.

{
[
\title<"Test file">
\unit<"mm">
**\tempo<"tempo [1/4] = 135", dy=15, fsize=12pt>**
\pageFormat<"215.9, 279.4, 10, 20, 10, 20">
\barFormat<style="system">
\instr<"Grand piano instrument", dx=10, dy=14, fsize=12pt>
]
,
[
\staff<1> \clef<"g"> \meter<"4/4", autoMeasuresNum="on"> c d e f g a]
}

**Comment by dfober** [comment]
it's finally done! \tempo supports font parameters (except for horizontal alignment)
