### ISSUE TITLE
Measure numbering

### ISSUE THREAD

**Issue by iv41879** [grame-cncm/guidolib#25]
I sow some newer features and options for measure numbering. Is it possible to do something like illustrated below? Left side is what we have now, right side is what I sow most often with printed scores that I have with me. Is it possible to add marking on these red marked numbers?

![measure-numbering](https://user-images.githubusercontent.com/6260936/27023837-8cd8aa54-4f54-11e7-9bb0-244964408d7e.png)

**Comment by dfober** [comment]
that's done (sorry for the long long delay)
