### ISSUE TITLE
build/Makefile isn't multi-processing safe

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#28]
Build fails:
```
gmake linux
gmake[3]: Entering directory '/usr/ports/print/guidolib/work/guidolib-1.63-src/build'
[ -d linux ] || mkdir linux
gmake -C linux
gmake[4]: Entering directory '/usr/ports/print/guidolib/work/guidolib-1.63-src/build'
gmake[4]: *** linux: No such file or directory.  Stop.
gmake[4]: Leaving directory '/usr/ports/print/guidolib/work/guidolib-1.63-src/build'
gmake[3]: *** [Makefile:180: linux/libGUIDOEngine.so] Error 2
gmake[3]: *** Waiting for unfinished jobs....
cd linux && cmake .. -G "Unix Makefiles" -DMIDIEXPORT=yes
```
unless -j 8 is removed.

This section in ```build/Makefile```  is related:
```
linuxcmake:
$(LINUX)/Makefile : CMakeLists.txt
        [ -d $(LINUX) ] || mkdir $(LINUX)
        cd $(LINUX) && cmake .. -G "Unix Makefiles" -DMIDIEXPORT=yes
```

It looks like it creates this directory and then something else immediately expects it to be filled.

Similar problems in Qt apps directories, like ```environments/Qt/apps/guido2image/build```.

You need to test build with high number of jobs, or on different OSes to catch these problems.

Observed on FreeBSD 11.1

**Comment by dfober** [comment]
should be fixed (and pushed). The dependencies are now linear.

**Comment by yurivict** [comment]
You fixed the library build, but later Qt apps again fail in case of -j N.

**Comment by dfober** [comment]
right! that's now fixed on Qt side too.

**Comment by yurivict** [comment]
Thank you for fixing this!
