### ISSUE TITLE
build/Makefile doesn't have 'install' target

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#29]
IMO, you need to just have a cmake build, and include Qt and other parts into it as options.

**Comment by dfober** [comment]
right! actually an install target makes sense on linux only and it exists in the generated linux makefile, thus the following should work:
 &gt; make -C linux install

I could add that to the main makefile, but it'll generate an error for other platforms (which is not very clean)
What do you mean with 
> have a cmake build, and include Qt and other parts into it as options ?

**Comment by dfober** [comment]
done! I've added an install target to the main makefile. Works on linux only.

**Comment by yurivict** [comment]
@dfober 

I tried to use the 'install' target, and got missing files. compared to the list of files I was getting installed with my script:
```
Error: Missing: bin/GuidoEditor
Error: Missing: bin/GuidoSceneComposer
Error: Missing: bin/guido2abstract
Error: Missing: bin/guido2image
Error: Missing: bin/guido2midi
Error: Missing: bin/guido2proll
Error: Missing: bin/guido2svg
Error: Missing: bin/guido2svgmap
Error: Missing: bin/guidoar2gr
Error: Missing: bin/guidodraw
Error: Missing: bin/guidogetpagecount
Error: Missing: bin/guidogetpagemap
Error: Missing: bin/guidogetstaffmap
Error: Missing: bin/guidogetsystemmap
Error: Missing: bin/guidogettimemap
Error: Missing: bin/guidogetversion
Error: Missing: bin/guidogetvoicecount
Error: Missing: bin/guidogetvoicemap
Error: Missing: bin/guidoparse
Error: Missing: bin/midi2proll
Error: Missing: include/guido/GDeviceQt.h
Error: Missing: include/guido/GFontQt.h
Error: Missing: include/guido/GSystemQt.h
Error: Missing: include/guido/Guido2Image.h
Error: Missing: include/guido/QGuidoGraphicsItem.h
Error: Missing: include/guido/QGuidoImporter.h
Error: Missing: include/guido/QGuidoPainter.h
Error: Missing: include/guido/QGuidoWidget.h
Error: Missing: include/guido/QPageManager.h
Error: Missing: lib/libGuidoQt.so
Error: Missing: lib/libGuidoQt.so.1
Error: Missing: lib/libGuidoQt.so.1.0
Error: Missing: lib/libGuidoQt.so.1.0.0
Error: Missing: share/fonts/guido/guido2.ttf
Error: Missing: share/icons/hicolor/128x128/apps/guidoeditor.png
Error: Missing: share/icons/hicolor/128x128/apps/guidoscenecomposer.png
Error: Missing: share/icons/hicolor/48x48/apps/guidoeditor.png
Error: Missing: share/icons/hicolor/48x48/apps/guidoscenecomposer.png
```

My 'install' script is:
```
do-install:
        ${INSTALL_PROGRAM} \
                ${WRKSRC}/environments/Qt/apps/GuidoEditor/GuidoEditor \
                ${WRKSRC}/environments/Qt/apps/GuidoSceneComposer/GuidoSceneComposer \
                ${WRKSRC}/environments/Qt/apps/guido2image/guido2image \
                ${WRKSRC}/src/tools/build/linux/midi2proll \
                ${WRKSRC}/src/tools/build/linux/guido* \
                ${STAGEDIR}${PREFIX}/bin
        @${MKDIR} ${STAGEDIR}${PREFIX}/include/guido
        ${INSTALL_DATA} \
                ${WRKSRC}/src/engine/include/*.h \
                ${WRKSRC}/platforms/linux/src/Cairo*.h \
                ${WRKSRC}/environments/Qt/libs/GuidoQt/include/*.h \
                ${STAGEDIR}${PREFIX}/include/guido
        ${INSTALL_LIB} \
                ${WRKSRC}/build/libGUIDOEngine.* \
                ${WRKSRC}/environments/Qt/libs/libGuidoQt.* \
                ${STAGEDIR}${PREFIX}/lib
        @${MKDIR} ${STAGEDIR}${PREFIX}/share/fonts/guido
        ${INSTALL_DATA} \
                ${WRKSRC}/src/guido2.ttf \
                ${STAGEDIR}${PREFIX}/share/fonts/guido
.for sz in 48 128
        @${MKDIR} ${STAGEDIR}${PREFIX}/share/icons/hicolor/${sz}x${sz}/apps
        ${INSTALL_DATA} \
                ${WRKSRC}/environments/Qt/package/debiansvn/usr/share/icons/hicolor/${sz}x${sz}/apps/* \
                ${STAGEDIR}${PREFIX}/share/icons/hicolor/${sz}x${sz}/apps
.endfor
```

**Comment by dfober** [comment]
that should be ok now (install target improved)
only the documentation (that is currently outdated) and the sample files are not installed. I could add them but is there any standard place for that?

**Comment by yurivict** [comment]
> only the documentation (that is currently outdated) and the sample files are not installed. I could add them but is there any standard place for that?

Makefiles aren't normally expected to install documentation and examples. However, you also use cmake. Normally, there is no need to use Makefile when there is cmake. You should get rid of Makefiles in favor of cmake. cmake usually accepts variables like '-DENABLE_EXAMPLES=ON', '-DENABLE_DOCUMENTATION=ON', `-DCMAKE_DOC_DIR:STRING=..."`

You also currently have mistakes in makefiles: this place https://github.com/grame-cncm/guidolib/blob/dev/environments/Qt/libs/Makefile#L4 should have these lines instead:
```
LIBDEST ?= $(DESTDIR)$(PREFIX)/lib
INCDEST ?= $(DESTDIR)$(PREFIX)/include/guido
```

```linuxinstall``` target there needs ```mkdir -p $(INCDEST)```.

**Comment by dfober** [comment]
That's done ( $(DESTDIR)$(PREFIX) ).
Regarding make and cmake, I'm using make as a wrapper around cmake, it makes projects maintenance far more easy across all the supported platforms (it starts to be a lot)

**Comment by yurivict** [comment]
This line https://github.com/grame-cncm/guidolib/blob/dev/environments/Qt/libs/Makefile#L14 should change to ```cp libGuidoQt.* $(DESTDIR)$(PREFIX)/lib``` because there is the option to use shared libs. (to not set ```CONFIG += staticlib```)

Before this line https://github.com/grame-cncm/guidolib/blob/dev/environments/Qt/apps/Makefile#L28, it should create the directories:
```
        mkdir -p $(SHARED)/applications
        mkdir -p $(SHARED)/icons/hicolor/48x48/apps
        mkdir -p $(SHARED)/icons/hicolor/128x128/apps
```

**Comment by yurivict** [comment]
```/usr``` in https://github.com/grame-cncm/guidolib/blob/dev/build/CMakeLists.txt needs to change to ```${PREFIX}```.

**Comment by dfober** [comment]
that's done (mkdir)
regarding CMakelists.txt, the variable was unused, I've removed the line
thanks for your feedback
