### ISSUE TITLE
Harmony branch is missing

### ISSUE THREAD

**Issue by yeonoson** [grame-cncm/guidolib#3]
Hello, I've been experimenting with guidolib recently. Unfortunately guidolib does not yet support harmonies, which are essential for my use case. However, prior to the move to github, there used to be a harmony_tag branch with simple - but nevertheless useful - support for harmonies. That branch and about 10 others are now gone. These branches were also deleted on the sourceforge repository.

Is there a reason for the removal? Can you at least restore the harmony_tag branch? Is there any chance to get the harmony_tag branch merged to dev?

**Comment by dfober** [comment]
Hi,

The migration to github came with a significant change in the development process: no more branches but pull requests.
All the deleted branches were supposed to be merged to dev but it might happen that it was not the case.
Actually managing a whole set of branches is no easy and I don’t remember what was on the harmony_tag branch (and even who created the branch)
Could you remind me what was on this branch and make sure it’s not part of the dev branch?
I’ll try to restore the branch on my side.
Best,
—
Dominique

**Comment by yeonoson** [comment]
I still have a local copy of the branch if that is of any help.

The branch was created on 2016-09-03 by J. Kilian, the latest change was on 2016-09-25. The branch adds support for the "\harmony" tag that allows to display chord-symbols above the staff. The main changes are contained in ARTextHarmony.h/cpp and GRTextHarmony.h/cpp. Related to this is the [harmony branch of libmusicxml](https://github.com/grame-cncm/libmusicxml/tree/harmony).

**Comment by dfober** [comment]
> Le 24 mars 2017 à 09:41, yeonoson <notifications@github.com> a écrit :
> 
> I still have a local copy of the branch if that is of any help.
> 
> The branch was created on 2016-09-03 by J. Kilian, the latest change was on 2016-09-25. The branch adds support for the "\harmony" tag that allows to display chord-symbols above the staff. The main changes are contained in ARTextHarmony.h/cpp and GRTextHarmony.h/cpp. Related to this is the harmony branch of libmusicxml <https://github.com/grame-cncm/libmusicxml/tree/harmony>.
> 
ok, there is a mistake here: you’re talking about the libmusicxml project (and not the guidolib)
actually the branch is still there:
	https://github.com/grame-cncm/libmusicxml/tree/harmony <https://github.com/grame-cncm/libmusicxml/tree/harmony>
it should be merged to the dev branch in a near futur and then be removed

**Comment by yeonoson** [comment]
These are really two different branches that only relate to each other:
- The **harmony** branch of libmusicxml allows to convert the <harmony> of MusicXML files to \harmony<text="...", dy=...> in guido notation. This branch still exists.
- The **harmony_tag** branch of guidolib allows to handle files with a \harmony tag. This branch is lost since the move to github.

**Comment by dfober** [comment]
> Le 24 mars 2017 à 09:58, yeonoson <notifications@github.com> a écrit :
> 
> These are really two different branches that only relate to each other:
> 
> The harmony branch of libmusicxml allows to convert the of MusicXML files to \harmony<text="...", dy=...> in guido notation. This branch still exists.
> The harmony_tag branch of guidolib allows to handle files with a \harmony tag. This branch is lost since the move to github.

ok, I never checkout this branch, that’s why I can’t see it
can you send it with a pull request ?

**Comment by yeonoson** [comment]
I just sent a pull request. As I am not yet that familiar with the code I cannot judge the quality of the code. I encountered following display flaw:
- If multiple \harmony tags map to the same note (as it happens sometimes for whole notes/breaks) the chord-symbols overlap.
- There is also no collision detection with other texts (e.g. tempo or mark) above the staff.

In my opinion, these do not hinder a merge to dev. If you agree I can open new issues for these.

**Comment by dfober** [comment]
> Le 25 mars 2017 à 01:02, yeonoson <notifications@github.com> a écrit :
> 
> I just sent a pull request. As I am not yet that familiar with the code I cannot judge the quality of the code. I encountered following display flaw:
> 
> If multiple \harmony tags map to the same note (as it happens sometimes for whole notes/breaks) the chord-symbols overlap.
> There is also no collision detection with other texts (e.g. tempo or mark) above the staff.
> In my opinion, these do not hinder a merge to dev. If you agree I can open new issues for these.
> 

Fine! and merged.
You have probably some examples of use, could you add one to the gan-examples folder?
Regarding the issues above : there is no global collision detection and the solution is to solve then manually  using dx, dy parameters. 
For the multiple \harmony tags issue, this is probably worth to open an issue with a gmn code example.

**Comment by yeonoson** [comment]
Example gmn file provided with #8.
