### ISSUE TITLE
In makefiles, please replace make with $(MAKE), and g++ with $(CXX)

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#30]
* make can have different names on different platforms.
* g++ is not the only C++ compiler

**Comment by dfober** [comment]
done for make (and pushed)
none of the scripts explicitly refers to g++, actually the compiler is detected by cmake (or qmake).
Setting CXX before calling cmake should do the job (in this case before calling make)

**Comment by yurivict** [comment]
There is still 'make' there:

https://github.com/grame-cncm/guidolib/blob/dev/environments/Qt/Makefile#L5

https://github.com/grame-cncm/guidolib/blob/dev/environments/Qt/apps/Make.shared#L44

**Comment by yurivict** [comment]
g++: https://github.com/grame-cncm/guidolib/blob/dev/src/tools/Makefile#L25

**Comment by dfober** [comment]
ok, that's done and pushed

**Comment by yurivict** [comment]
'make' is still in the github version, ex. https://github.com/grame-cncm/guidolib/blob/dev/environments/Qt/Makefile
