### ISSUE TITLE
Please add 'if defined(__FreeBSD__)'

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#31]
In .cpp and .h: ```s/elif linux/elif defined(linux) || defined(__FreeBSD__)/```

I verified, it builds in the FreeBSD.

**Comment by dfober** [comment]
Could you list the files (I've made a recursive grep but didn't find anything)
or better: a pull request

**Comment by yurivict** [comment]
https://github.com/grame-cncm/guidolib/pull/34
