### ISSUE TITLE
Please remove the hard-coded /usr/include and /usr/lib from build/CMakeLists.txt

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#32]
cmake has special variables that contain platform-dependent values for headers and libs.

**Comment by dfober** [comment]
not obvious to find in the cmake documentation. If you have any pointer or the name of these variables, I'll happy to use them.

**Comment by yurivict** [comment]
${CMAKE_INSTALL_PREFIX} is where it is going to be installed.

**Comment by dfober** [comment]
ok, that's done. Note that I set the CMAKE_INSTALL_PREFIX to _/usr_ (makes the life easier) unless user defined.
