### ISSUE TITLE
github version fails to build

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#35]
When I switched from sourceforge to github to see the latest changes, this error showed up:

```
===================================
Build guido2image for linux done
===================================
gmake[9]: Leaving directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/guido2image/build'
gmake[8]: Leaving directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/guido2image/build'
gmake[7]: Leaving directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/guido2image/build'
gmake -C GuidoEditor/build
gmake[7]: Entering directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/GuidoEditor/build'
gmake -f ../../Make.shared PROJECT=GuidoEditor 
gmake[8]: Entering directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/GuidoEditor/build'
gmake -f ../../Make.shared linux
gmake[9]: Entering directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/GuidoEditor/build'
gmake -C linux -f GuidoEditor.makefile
gmake[10]: Entering directory '/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/GuidoEditor/build/linux'
clang++ -pthread -Wl,-rpath,/usr/local/lib/qt5 -o GuidoEditor CodeEditor.o GuidoHighlighter.o main.o MainWindow.o MusicNotationHighlighter.o QFindWidget.o SetupDialog.o qrc_application.o moc_CodeEditor.o moc_MainWindow.o moc_QFindWidget.o moc_SetupDialog.o   -L/usr/local/lib -L/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/GuidoEditor/../../libs -lGuidoQt -L/usr/ports/audio/guidolib/work/guidolib-4ef8d02/environments/Qt/apps/../../../build/linux -L/usr/ports/audio/guidolib/work/guidolib-4ef8d02/build -lGUIDOEngine -L/usr/local/lib/qt5 -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL 
MainWindow.o: In function `MainWindow::updateDisplayState()':
../../MainWindow.cpp:(.text+0xa9dc): undefined reference to `GuidoShowElement'
../../MainWindow.cpp:(.text+0xa9f2): undefined reference to `GuidoShowElement'
../../MainWindow.cpp:(.text+0xaa08): undefined reference to `GuidoShowElement'
../../MainWindow.cpp:(.text+0xaa1e): undefined reference to `GuidoShowElement'
../../MainWindow.cpp:(.text+0xaa34): undefined reference to `GuidoShowElement'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dfober** [comment]
This is likely due to new files to the project. In this case, you should re-run cmake. The simplest way is to `touch CmakeLists.txt` before running `make`. This is one limitation of the current makefile: it doesn't detect new files. Maybe it should always run cmake.
Note that you should use github rather than sourceforge. github is always up-to-date which is not the case with sourceforge.

**Comment by yurivict** [comment]
> This is likely due to new files to the project. In this case, you should re-run cmake.

No, 647290c breaks in freshly checked out build.

**Comment by dfober** [comment]
did you re-compile the guido library? GuidoShowElement is actually implemented in GUIDOEngine.cpp, thus my previous hypothesis was wrong but I didn't notice that the error was generated while compiling guido2image. Make sure the Guido library is up-to-date.

**Comment by yurivict** [comment]
> Make sure the Guido library is up-to-date.

No, the problem is that the build picks up the old, pre-installed version of guidolib. I had to delete it for the build to succeed.

**Comment by dfober** [comment]
I'm afraid there is no solution to that: I think the system picks the first library found and looks for standard places first. When the library is installed, the installed one is used, otherwise the -L option takes effect. You have to uninstall the library to use the freshly compiled one, or to install the freshly compiled library.
