### ISSUE TITLE
'guido2image -t GIF' doesn't produce a result

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/guidolib#38]
This command
```
guido2image -t GIF -f octava.gmn -o octava.gmn.gif
```
doesn't produce any output, but this one
```
guido2image -t PNG -f octava.gmn -o octava.gmn.png
```
does.

**Comment by dfober** [comment]
this is probably because the gif plugin is not available (provided by Qt)

**Comment by yurivict** [comment]
I see, you are right. So, you need to print the message when Qt fails. For me, ```image.save(...);``` returns ```false```. You should just print the error message that Qt doesn't support GIF and exit.

**Comment by dfober** [comment]
done. The `image.save` status is now propagated and generates an error code and an error message with guido2image
