### ISSUE TITLE
Clef spacing problem in presence of Empty Staves

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#46]
In multi-staves scores, with presence of multiple voices (such as a regular piano scores), `\clef` tag in the middle of a measure produces excessive empty space.

Render attached score and look at measures 2 and 5:

[GuidoClefBug.gmn.txt](https://github.com/grame-cncm/guidolib/files/1317889/GuidoClefBug.gmn.txt)

Note that if you remove the empty `\staff<3>` in the end the bug disappears. I reduced this from a complex score where the `\staff<3>` voice had lots of `\empty` tags for voicing.

**Comment by dfober** [comment]
This issue is similar to [issue #18](https://github.com/grame-cncm/guidolib/issues/18).
Adding an `empty` element after the `c` note solves the problem.
For an optimal rendering, each voice should be fully written (i.e. up to the end of the score), which gives a full control over the spacing.
