### ISSUE TITLE
Slur collision with beamed sequence

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#47]
Slur tag on a beamed sequence can lead to the collision of slur with note/chords. Example:

<code>
[\clef<"f4"> \key<-1> \meter<"2/4"> _/8 \stemsDown \slurBegin:1<curve="up"> \beam( c0/8 { a/8, c1/8 } f0/8) \slurEnd:1]
</code>

Screenshot: 
<img width="483" alt="screen shot 2017-09-22 at 23 30 32" src="https://user-images.githubusercontent.com/3298204/30765165-7fcdbea4-9fee-11e7-9dfb-d87b00961865.png">

**Comment by dfober** [comment]
fixed
