### ISSUE TITLE
Crescendo rendering bug on single Chord

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#48]
Render the following snippet in Guido 

<code>
{ [ \staff<1>  
   (* meas. 1 *)  \clef<"g2"> \key<-2> \meter<"3/4">  _*3/4 \bar 
   (* meas. 2 *)  \beamsOff { a&0/4, c1/4, f/4 } \crescBegin \beamsOff { a&0/2, b&/2, f1/2 } \crescEnd \bar 
 ]
 }
</code>

Measure 2 should show a simple _crescendo_ on the second chord. It is actually rendered as a vertical line on the note:
 
<img width="285" alt="screen shot 2017-09-26 at 00 56 58" src="https://user-images.githubusercontent.com/3298204/30834942-cbbbe2d2-a255-11e7-9d50-34a6504eb73b.png">

I believe this has something to do with the range of the Crescendo when it begins and ends before and right after the same note/chord.

**Comment by dfober** [comment]
Right, that should be catched by the rendering engine.
A work around using the tag parameters:
`{ 
	[ \staff<1> 
	(* meas. 1 *) \clef<"g2"> \key<-2> \meter<"3/4"> _*3/4 \bar 
	(* meas. 2 *) \beamsOff { a&0/4, c1/4, f/4 } 
	 \cresc<dx1=-2, dx2=4, deltaY=2, autopos="on">( \beamsOff { a&0/2, b&/2, f1/2 }) \bar 
	] 
}`

**Comment by arshiacont** [comment]
That's true but I'm actually _generating_ these GMNs from MusicXML and I can't think of an automatic way of deciding the values of _dx1_ and _dx2_ but maybe you have an idea?!

Auxiliary question: How does `autopos="on"` behave with dx1, dx2 and dy parameters? In conflict with dy maybe?

**Comment by dfober** [comment]
`autopos` affects only the `y` position, thus it's independent from `dx`.
`dy` is applied to the computed position when `autopos=on`

**Comment by dfober** [comment]
Regarding an automatic way of deciding the values of dx1 and dx2, that should be computed by the engine since the required information is available. Otherwise, the values used in the proposed workaround should work in most cases.

**Comment by arshiacont** [comment]
@dfober Actually if there is one bug that we'd love to see corrected is this one since there's no way I can integrate a general work-around.

The bug seems to be on the rendering side. It seems actually fine when the dynamic is one a single-note but not when on a single-chord. Here is a sample:

`{[  
   (* meas. 1 *)  \clef<"f4"> \key<1> \meter<"4/4", autoMeasuresNum="system"> \crescBegin<deltaY=2.8hs, dy=0hs> d/1 \crescEnd 
   (* meas. 2 *)  \crescBegin<dy=0hs>  {a0/1, c1/1 } \crescEnd
 ]
}`

**Comment by dfober** [comment]
fixed and pushed to git (dev branch).
