### ISSUE TITLE
Key change rendering offset bug

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#49]
Render the following sample score 
[keyChangePolyphonicBug.txt](https://github.com/grame-cncm/guidolib/files/1340106/keyChangePolyphonicBug.txt)

The generated key change gets unwanted offset as in this screenshot and systematically everytime a key change appear in the same score pattern 

![guidoeditorkeychangebug](https://user-images.githubusercontent.com/3298204/30956942-0d7d1788-a439-11e7-9f81-d3fe7d27ba31.png)

**Comment by dfober** [comment]
Commenting the `\staffFormat` tag before the key change solves this issue. There are many `\staffFormat` with `dy` attributes which are a bit incomprehensible to me.  `\staffFormat` makes sense at the beginning of a staff, but conflicting `\staffFormat`s (i.e. with different `dy`values)  in the middle of a voice are really strange.

**Comment by arshiacont** [comment]
Make sense! I am removing local inference of staffFormat from MusicXML conversion as a consequence and stick to the global declarations. Thanks.
