### ISSUE TITLE
Incorrect Slur slope with explicit Stem Directions

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#50]
The slope is corrected if we inverse the Stem directions of the first Beam Group.

Probably similar to #47 

<code>
{  [
   \clef<"g2"> \key<-2> \meter<"2/4"> \intens<"mf", dy=-3.6hs, dx=-1>( _/16) \stemsDown \slurBegin:1<curve="up"> \beam( d2/16 \stemsUp \grace( f/8) \dimBegin<dy=-2.6hs> \stemsDown e&/16 d/16) \beam( e&/16 c/16 b&1/16 \dimEnd a/16) \slurEnd:1 \bar 
    ]
}
</code>

**Comment by dfober** [comment]
fixed with slur slope limitation
