### ISSUE TITLE
GuidoGetMeterAt bug (returns zero on Count)

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#53]
On the (simple) attached score [gmn-getMeterAt0Error.txt](https://github.com/grame-cncm/guidolib/files/1545041/gmn-getMeterAt0Error.txt) run the following command from the API:

```
    GuidoDate guidoDate;
    guidoDate.num = 0;
    guidoDate.denom = 1;
    GuidoMeter meter;
    GuidoGetMeterAt(self.arHandler, 1, guidoDate, meter);
```

which leads to `meter.count[0]` being equal to _zero_, which is wrong! This is a simple 2/4 piece.

**Comment by arshiacont** [comment]
for info, using `GuidoGetMetersAt(...)` produces the same error.

**Comment by dfober** [comment]
That's fixed and pushed to the dev branch. The bug was due to cue notes that are stored in separate additional voices.
