### ISSUE TITLE
Include height and width in SVG

### ISSUE THREAD

**Issue by murkle** [grame-cncm/guidolib#55]
SVGs work better(?differently) in browsers (eg plotting on HTML5 canvas) if they have height and width ie
`<svg width = "479" height = "253" viewBox="0 0 479 253"`
instead of just
`<svg viewBox="0 0 479 253"`

so an option to include those would be useful

**Comment by dfober** [comment]
Specifying only the viewBox leaves room for the browser to decide on the viewport. 
There is now a `-viewport` option in guido2svg.
