### ISSUE TITLE
Juce examples are not compiling

### ISSUE THREAD

**Issue by Bk8** [grame-cncm/guidolib#57]
Juce examples where made with an old version of Juce, and are not compiling a lot of header files are not found.

**Comment by Wah0airo** [comment]
I compiled the Juce examples with Juce 5.2.1,  all works perfectly, maybe you have errors with the Producer configuration. You should add some "override" keywords, but this should not be a big problem

**Comment by dfober** [comment]
The GuidoViewer.jucer has been updated (actually 2 months ago) to Juce version 5.3.2 and it compiles correctly. Note that the project depends on where Juce is installed and may require adaptation.
