### ISSUE TITLE
Beamed Staccato positioning rendering problem

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#64]
When used on a Beamed sequence, the `stacc` tag with placement parameters do not adapt to the stem length leading to chaotic rendering.

Example with screenshot (using latest Guidolib compile):

`{[ \staff<1>  
   (* meas. 1 *)  \clef<"f4"> (* meas. 1 *)  \stemsDown \beamBegin:1 
 \stacc<position="below">( c-1/8)
 \stacc<position="below">( c0/8)
 \stacc<position="below">( c-1/8)
 \stacc<position="below">( c0/8)
 \stacc<position="below">( c-1/8)
 \stacc<position="below">( c0/8)
 \beamEnd:1  ]
 , 
[ \staff<2> \staffFormat<dy=-6>  
   (* meas. 1 *)   \stemsUp \beamBegin:1 \stacc<position="above">( e0/8)
 \stacc<position="above">( f/8)
 \stacc<position="above">( g/8)
 \stacc<position="above">( e/8)
 \stacc<position="above">( f/8)
 \stacc<position="above">( g/8)
 \beamEnd:1 ]
  }`

![screenshot 2019-02-13 at 16 17 40](https://user-images.githubusercontent.com/3298204/52721935-f9004100-2faa-11e9-981d-af34cce97498.png)

**Comment by dfober** [comment]
Fixed and pushed to git (dev branch)

**Comment by arshiacont** [comment]
Marvelous! Works like a charm
