### ISSUE TITLE
Incorrect Slur rendering between grace and normal note

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#65]
Slur between a grace note and proceeding normal note is rendered from the grace note to the STEM of the proceeding note (whereas it should be to the note).

Example:
`{[ 
   (* meas. 1 *)  \clef<"g2"> \key<-1> \meter<"2/4"> \stemsUp \grace( \slurBegin:1<curve="down"> \beamsOff g#2/8)
 \stemsDown \beamBegin:1 \stacc<position="above">( a/8)
 \slurEnd:1 \stemsUp \grace( \slurBegin:1<curve="down"> g#/8)
 \stemsDown \stacc<position="above">( a/8)
 \beamEnd:1 \slurEnd:1 \beamBegin:1 \accent<position="above">( c3/8.)
 b2/16 \beamEnd:1 \bar 
   (* meas. 2 *)  \stemsUp \grace( \slurBegin:1<curve="down"> \beamsOff g#/8)
 \stemsDown \beamBegin:1 \stacc<position="above">( a/8)
 \slurEnd:1 \stemsUp \grace( \slurBegin:1<curve="down"> g#/8)
 \stemsDown \stacc<position="above">( a/8)
 \beamEnd:1 \slurEnd:1 \beamBegin:1 \accent<position="above">( c3/8.)
 d/16 \beamEnd:1 ]
  }`

Rendering in Guido:
![screenshot 2019-02-14 at 17 36 33](https://user-images.githubusercontent.com/3298204/52802034-5ebdfd00-307f-11e9-99c1-c3765f58635d.png)

Correct rendering:
<img width="366" alt="screenshot 2019-02-14 at 17 37 16" src="https://user-images.githubusercontent.com/3298204/52802053-6c738280-307f-11e9-9986-32b80a95115a.png">

**Comment by dfober** [comment]
fixed and pushed to dev branch.
Makes use of specific anchor points triggered only with one grace note and one note. 
Makes use of the normal behaviour when the slur encompasses more notes.
