### ISSUE TITLE
Embedded Arpeggio in a Text Tag moves the hairpin

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#71]
Test case:
```
{[  
   _/8  \text<"dim.", dy=-8hs>(\stemsUp \beamBegin:1 \arpeggio( {a0/8, d1/8, f#/8, a/8  }))
 _/8 \stemsUp \arpeggio( {a0/8, d1/8, f#/8, a/8  })
 \beamEnd:1 ]
  }
```

Results to:
![Screenshot 2019-03-21 at 10 54 41](https://user-images.githubusercontent.com/3298204/54744611-c0fea600-4bc7-11e9-8d5d-c56ed53b8115.png)

**Comment by dfober** [comment]
fixed and pushed to dev branch
