### ISSUE TITLE
Beam Rendering Bug on Cross Staff Notes

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#73]
The following Guido excerpt:
```
{[ \staff<1> \staffFormat \accol<id=0, range="1-2"> \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"g2"> \key<-2> \meter<"3/8"> \intens<"p", dy=-2.6hs> _/4. \bar 
   (* meas. 2 *)  \stemsDown \beamsOff a/4 \slurEnd:1 _/8 ]
 , 
[ \staff<2>  
   (* meas. 1 *)  \clef<"f4"> \key<-2> \meter<"3/8">  \stemsDown \beamBegin:1 d-1/16 \stemsDown a/16 \stemsDown f#0/16 \beamEnd:1 \stemsDown \beamBegin:1 a/16 d1/16 \staff<1> f#/16 \beamEnd:1 \staff<2> \bar 
   (* meas. 2 *)  \noteFormat<dx=-2>( _*3/8)
 ]
  }
``` 

Results into 
![Screenshot 2019-04-16 at 14 33 34](https://user-images.githubusercontent.com/3298204/56209799-ab5c8f00-6054-11e9-9504-77927260366e.png)

with expected behavior such as in:
<img width="471" alt="Screenshot 2019-04-16 at 14 34 30" src="https://user-images.githubusercontent.com/3298204/56209830-c3cca980-6054-11e9-98a7-3ae4c76cb9ab.png">

**Comment by arshiacont** [comment]
A second example / Unit-test (might be the same bug):

```
{[ \staff<1> \accol<id=0, range="1-2"> \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"f4"> \key<2> \meter<"6/8", autoBarlines="off", autoMeasuresNum="system"> empty*3/4 \bar 
   (* meas. 2 *)  _*3/4 \bar 
   (* meas. 3 *)  _*3/4  ]
 ,  
[ \staff<2> \staffFormat<dy=-13> 
   (* meas. 1 *)  \clef<"f4"> \key<2> \meter<"6/8", autoBarlines="off", autoMeasuresNum="system"> \stemsUp \beamBegin:1 \arpeggio( \stacc<position="below">( {a-1/8, d0/8, f#/8  })
)
 \staff<1> \stemsDown \stacc<position="above">( {d/8, d1/8  })
 \staff<2> \stemsUp \stacc<position="below">( {a-1/8, d0/8, f#/8  })
 \beamEnd:1 \staff<1> \stemsDown \beamBegin:1 \stacc<position="above">( {d/8, d1/8  })
 \staff<2> \stemsUp \arpeggio( \stacc<position="below">( {a-1/8, d0/8, f#/8  })
)
 \staff<1> \stemsDown \stacc<position="above">( {d/8, d1/8  })
 \beamEnd:1 \staff<2> \bar 
   (* meas. 2 *)  \stemsUp \beamBegin:1 \arpeggio( \stacc<position="below">( {a-1/8, d0/8, f#/8  })
)
 \staff<1> \stemsDown \stacc<position="above">( {d/8, d1/8  })
 \staff<2> \stemsUp \stacc<position="below">( {a-1/8, d0/8, f#/8  })
 \beamEnd:1 \staff<1> \stemsDown \beamBegin:1 \stacc<position="above">( {d/8, d1/8  })
 \staff<2> \stemsUp \arpeggio( \stacc<position="below">( {a-1/8, d0/8, f#/8  })
)
 \beamEnd:1 _/8 \bar 
   (* meas. 3 *)  _*3/4  ]
  }
```

rendered as 
![Screenshot 2019-04-16 at 14 44 24](https://user-images.githubusercontent.com/3298204/56210541-56ba1380-6056-11e9-9839-1745b280ace1.png)

ideal result:
<img width="527" alt="Screenshot 2019-04-16 at 14 44 18" src="https://user-images.githubusercontent.com/3298204/56210556-5d488b00-6056-11e9-8767-cd5ef9099e8b.png">

**Comment by dfober** [comment]
I suspect that won't be easy to fix, thus be patient...

**Comment by dfober** [comment]
Not the same bug.
The second issue (wrong stem direction) is solved.
The first one is still pending.

**Comment by arshiacont** [comment]
Thank you Dominique. Let me know if I can be of any help for the first issue.

**Comment by dfober** [comment]
fixed and pushed to dev branch

**Comment by arshiacont** [comment]
@dfober I don't see any associated commit on GitHub:
https://github.com/grame-cncm/guidolib/commits/dev
`git push`? :)

**Comment by dfober** [comment]
commit 3982421c6cbea5795401c7a22bdcd6caece6971f

**Comment by arshiacont** [comment]
Thank you @dfober .

While testing this excerpt:
```
{[ \staff<1>  \auto<autoInstrPos="on"> \barFormat<style= "system", range="1"> 
   (* meas. 1 *)  \clef<"g2"> \key<0> \meter<"3/8">  _*3/8 \bar 
   (* meas. 2 *)  _*3/8 \bar 
   (* meas. 3 *)  _*3/8 ]
 , 
[ \staff<2>  \auto<autoInstrPos="on"> \accol<id=0, range="2-3"> \barFormat<style= "system", range="2-3"> 
   (* meas. 1 *)  \clef<"g2"> \key<-2> \meter<"3/8"> _*3/8 \bar 
   (* meas. 2 *)  \intens<"p", dy=-0.6hs> _/4. \bar 
   (* meas. 3 *)  \stemsDown \beamsOff a1/4 \slurEnd:1 _/8]
 , 
[ \staff<3> 
   (* meas. 1 *)  \clef<"f4"> \key<-2> \meter<"3/8">  \stemsDown \slurBegin:1<curve="up"> \beamBegin:1 g-1/16 \stemsDown b&/16 \stemsDown d0/16 \stemsDown g/16 \beamEnd:1 \stemsUp \beamBegin:1 b&/16 \stemsUp d1/16 \beamEnd:1 \bar 
  \bar 
   (* meas. 2 *)  \stemsDown \slurBegin:1<curve="up"> \beamBegin:1 d-1/16 \stemsDown a/16 \stemsDown f#0/16 \beamEnd:1 \stemsDown \beamBegin:1 a/16 \stemsDown d1/16 \staff<2> \stemsDown f#/16 \beamEnd:1 \staff<3> \bar 
   (* meas. 3 *)  \noteFormat<dx=-2>( _*3/8)
   ]
  }
```

I get the following with incorrect beaming on measure 2-Staves 2&3:
![Screenshot 2019-04-25 at 15 41 53](https://user-images.githubusercontent.com/3298204/56740162-adb79b00-6770-11e9-8a3d-f7237791bfb0.png)

If I remove staff 1 entirely, everything is back in order.

Am I doing something wrong here?!

**Comment by dfober** [comment]
I think I finally hate this kind of problem. ;-)

**Comment by dfober** [comment]
fixed and pushed to dev branch.
Note that there is still room for improvements, especially for beaming starting with a note outside the staff (e.g. stems up and c1 on f clef) .

**Comment by dfober** [comment]
...and improved (regarding the remark above).

**Comment by arshiacont** [comment]
Thank you Dominique! Works like a charm and tested! 

Let me know what are your favourite problems and I'll focus on them from now on.. ;)
