### ISSUE TITLE
Support sfz and rfz in Intensity tag

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#74]
The use of "sfz" (sforzando) and "rfz" (rinforzando) are common to indicate Intensities in music scores. It would be nice to add them especially if it's not much effort.

https://en.wikipedia.org/wiki/Sforzando

**Comment by dfober** [comment]
requires the guido font to be extended. Should be easy for "sfz" ("sf" is already there and "fz" too), more complex for "rfz" ... Any font designer to help?

**Comment by dfober** [comment]
ok, that's done and pushed to dev branch
