### ISSUE TITLE
Tremolo number of Strike Bug

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#75]
It seems like the number Strikes rendered in Guido is always one less than the indicated number!?

```
{[ \clef<"g2"> \key<1> \meter<"3/4"> 
 \stemsUp \trem<style="/">( g/8)
 \stemsUp \trem<style="//">( b/8) 
 \stemsUp \trem<style="///">( d1/8)
 \stemsUp \trem<style="////">( g/8) 
 \stemsDown \trem<style="//">( b/8)
 \stemsDown \trem<style="/">( d2/8)
  ]
  }
```

leads to 
![Screenshot 2019-04-19 at 17 53 26](https://user-images.githubusercontent.com/3298204/56431977-0cda6300-62cc-11e9-826d-b94b76fa07d1.png)

**Comment by dfober** [comment]
Actually, the \trem tag takes account of the current note duration. Try using quarter notes:
~~~~~
[
	\clef<"g2"> \key<1> \meter<"3/4"> 
	\stemsUp \trem<style="/">( g/4)
	\stemsUp \trem<style="//">( b) 
	\stemsUp \trem<style="///">( d1)
	\stemsUp \trem<style="////">( g) 
	\stemsDown \trem<style="//">( b)
 	\stemsDown \trem<style="/">( d2)
]
~~~~~
and you'll get what you expect. However the semantic vs graphic strategy is questionable. 
What's your idea about that?

**Comment by arshiacont** [comment]
Well, if I do as you say I'll obtain two measures (as expected) as follows:
![Screenshot 2019-04-23 at 12 00 30](https://user-images.githubusercontent.com/3298204/56572493-7786e980-65bf-11e9-94f4-520137ef65f6.png)

This is different from what is notated.

If it's simple, I believe we should decouple the duration semantic from Tremolo and just draw strikes if they are indicated. From what I see there is always an ambiguity on the meaning of strikes indicating repetition so we might want to leave this to the discretion of the user.

The example above actually comes from an official edition.

**Comment by dfober** [comment]
Here is what I get:
<img width="738" alt="Capture d’écran 2019-04-23 à 16 00 12" src="https://user-images.githubusercontent.com/431043/56587058-2a1b7400-65e1-11e9-9384-b5ea38e31069.png">
could you check your output?

Otherwise, I agree with the graphical semantic and I'll modify to draw strikes as indicated.

**Comment by arshiacont** [comment]
@dfober What you get is correct if duration is changed to `/4` however the original score is in `/8` with only one measure (instead of two). 
What I want to achieve is this: 
<img width="133" alt="Screenshot 2019-04-23 at 16 07 18" src="https://user-images.githubusercontent.com/3298204/56587481-eaa15780-65e1-11e9-9351-12ad4528f1d3.png">

Hence my request... . :)

**Comment by dfober** [comment]
I think there is some confusion here: 
- how can the result you show me above (your last post) correspond to the code posted at the beginning of this thread?
- same question for the message 2 posts before (with only the duration changed from /8 to /4)? that was the meaning of my question: "could you check", which I re-formulate: how can you get the same single strike using style attributes with different strokes count? or are you using a code different from the one you've posted?

I've changed the semantic to a graphical semantic. That's pushed to git. Is it what you're expecting?

**Comment by arshiacont** [comment]
You are right! Sorry about that!!! I changed the first post GMN to reflect the bug. But what I'm really expecting is this:
```
{[ \staff<1>  
   (* meas. 1 *)  \clef<"g2"> \key<1> \meter<"3/4"> 
 \stemsUp \trem<style="/">( g/8)
 \stemsUp \trem<style="/">( b/8) 
 \stemsUp \trem<style="/">( d1/8)
 \stemsUp \trem<style="/">( g/8) 
 \stemsDown \trem<style="/">( b/8)
 \stemsDown \trem<style="/">( d2/8)
  ]
  }
```
<img width="133" alt="Screenshot 2019-04-23 at 16 07 18" src="https://user-images.githubusercontent.com/3298204/56594471-30175200-65ed-11e9-9a13-b2b164b34b25.png">

I'll check the Repo and will come back here swiftly.

**Comment by arshiacont** [comment]
Just tested. Perfect! Thanks.
