### ISSUE TITLE
Accidental on Tied notes should not appear on Measure Change

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#78]
Currently Accidentals accross tied notes between two measures are rendered on the new Measure. For example:
```
{[ (* meas. 1 *)  \clef<"g2"> \key<-3> \meter<"3/8"> 
   (* meas. 2 *)  \stemsDown \beamBegin:1 e&/8 d/8  \tie( e/8 \beamEnd:1 \bar 
   (* meas. 3 *)  \stemsDown \beamBegin:1 e/8) d/8  \tieBegin c#/8 \beamEnd:1 \bar 
   (* meas. 4 *)  \stemsDown \beamBegin:1 c#/8 \tieEnd a&1/8 c#/8 \beamEnd:1 ]}
```
leading to:
![Screenshot 2019-05-02 at 18 46 39](https://user-images.githubusercontent.com/3298204/57091951-a4977280-6d0a-11e9-9736-3e5c24dd69cd.png)

I believe (but not sure) that _convention_ in this case is to avoid repeating the accidental and bringing it back (in measure 4 above) if the same note is repeated... : https://music.stackexchange.com/questions/33533/what-conventions-are-used-with-accidentals-and-tied-notes

[low priority]

**Comment by dfober** [comment]
Actually this is acceptable (according to Gould - Behind Bars p.81). In addition, this can be solved at language level using \acc<style="none">(c#).

**Comment by dfober** [comment]
that's fixed but using a global setting: \set or \auto tag parameter 'autoHideTiedAccidentals'
see https://guidodoc.grame.fr/refs/tags/Miscellaneous/
the default value is off by default to preserve the existing behavior, however it would seem logical to set it to true. What do you think?

**Comment by arshiacont** [comment]
After talking to some of our experts: It seems like showing accidental on ties is only useful when the tie is on two consecutive Pages. So I'd say let's keep this as default behavior.
Since Paging is a Layout issue, I believe users can use cautionaries instead.

**Comment by dfober** [comment]
...starts to be a bit confused to me... 
Currently the 'autoHideTiedAccidentals' parameter has been changed to 'on' by default (not yet reflected by the documentation). Should I revert it to 'off' or leave it as is?

**Comment by arshiacont** [comment]
oh no! Sorry.. didn't see that. It should be "on" by default. Closing Ticket here.
