### ISSUE TITLE
Help finding beat position

### ISSUE THREAD

**Issue by isaquevieira** [grame-cncm/guidolib#82]
Hello, I need some help to get the position of the beats. I searched through the documentation and couldn't figure it out how to do it.
I'm running guidolib 1.6.7 on iOS.

**Comment by dfober** [comment]
Could you clarify what you mean by "get the position of the beat" ? What do you want to get: the time position? the graphic position? Are you using the Guido library? are you looking for an API for that?

**Comment by isaquevieira** [comment]
Basically what I want to do is show a cursor above a score (that I'm already able to show using Guido library) and I need to get the graphical positions where it should jump. If you could give me a direction I would be really thankful.
Answering your questions: 1 - I need both. 2 - Yes, I'm using the Guido library. 3 - A already built-in API for that would be really great, I wasn't sure if that existed or not.

**Comment by arshiacont** [comment]
Hi @isaquevieira 

GuidoLib comes with several Maps. Depending on how you architecture your software it is easy to convert back and forth between `Dates` (or Beat time) and `Segment` (graphical positions.
Have a look at `GuidoScoreMap.h` and especifically `GuidoGetTime` and `GuidoGetPoint` methods.
You initialize the Maps separately once your score is built.
We already do this in the Metronaut App on iOS which is proudly using GuidoLib.

Cheers,

Arshia

**Comment by isaquevieira** [comment]
Thank you, @arshiacont. I'll checkout those functions.

**Comment by isaquevieira** [comment]
Just another question: How can I get the metronome mark note? For instance, if I have this tag on the gmn file `\tempo<"[3/8] = 62">`, what's the API for getting this mark note?

**Comment by dfober** [comment]
There is no such API. Explain me what you need and I could create one.
Note that MIDI export contains this information.

**Comment by isaquevieira** [comment]
Sorry for the trouble. Thank you very much for your time.
What I want is a list of the metronomes with the start time, beat unit and the bpm.

**Comment by dfober** [comment]
That's done. There is a new `GuidoGetTempoList` API. See the GUIDOEngine.h header for more information. 
You'll have to recompile the dev branch to get it.
