### ISSUE TITLE
MacOS CMake generation error

### ISSUE THREAD

**Issue by danomatika** [grame-cncm/guidolib#84]
On macOS 10.14, generating a makefile with CMake fails with:

~~~
CMake Error at CMakeLists.txt:227 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  statictarget
~~~

This appears to be due to the "statictarget" name not expanding in CMakeLists.txt. Changing it to `${statictarget}` on the affected line fixes the issue.

**Comment by dfober** [comment]
right, it was an incorrect variable reference . That's fixed.
