### ISSUE TITLE
Slur rendered incorrectly on beamed sequence

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#87]
Example:
```
{ 
[ 
\clef<"f4"> \key<-1> \meter<"6/8"> \stemsUp \slurBegin:1<curve="up"> \beamBegin:1 f0/8 \beamBegin:2 b&/16 d1/16 \beamEnd:2 f/8 \slurEnd:1 \beamEnd:1 empty*3/8 ]
  }
```

Resulting to 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/3298204/63764934-3b92c680-c8c8-11e9-9ccb-66c97a7fa070.png">

**Comment by dfober** [comment]
Fixed! (with the issue #94)
