### ISSUE TITLE
Incorrect Beam Duration on Cross Staff chords

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#88]
Unit test:
```
{[ \staff<1> 
\clef<"g2"> \key<2> \stemsUp 
\beamBegin:1 { \staff<2> f0/8.., \staff<1> f1/8..} 
{\staff<2>e0/32, \staff<1>e1/32} 
\beamEnd:1  
]
 , 
[ \staff<2> \clef<"f4"> \key<2>  ]
 }
```
leads to
<img width="447" alt="image" src="https://user-images.githubusercontent.com/3298204/63899336-caa0fb00-c9fc-11e9-9834-d9ff4aa20da3.png">

Where as its non-cross-staff leads to 
```
{[ \staff<1> 
\clef<"g2"> \key<2>  
\beamBegin:1 f1/8.. e1/32 \beamEnd:1  
]
 , 
[ \staff<2> \clef<"f4"> \key<2>  ]
 }
```
<img width="345" alt="image" src="https://user-images.githubusercontent.com/3298204/63899437-2f5c5580-c9fd-11e9-802a-12f838469811.png">

Note also how on the Cross-Staff version we miss the Clef and Key Signature on Staff 1 (probably because he first event is on another staff?!).

**Comment by dfober** [comment]
fixed
