### ISSUE TITLE
Add support for Bow Strokes

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#89]
Suggestion to add support for Up and Down Bow Strokes, very useful for all chords.

https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-up-bow.htm
and 
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-down-bow.htm

It can conform to other articulations with parameter _placement_ taking values "above" or "below" (or whatever is already in place in Guido as Tag Parameter)

**Comment by dfober** [comment]
done

**Comment by arshiacont** [comment]
Thanks @dfober . Maybe `git push` ? :)

**Comment by dfober** [comment]
right !
really done now :-)

**Comment by arshiacont** [comment]
Wow! Now I understand why I didn't see all you told me in the past few weeks.. you should push more often hahaha :D

**Comment by arshiacont** [comment]
@dfober Shouldn't there be new Symbols in the Font? I don't see any updates to guido2.ttf + on https://guidoeditor.grame.fr/ when running 
```
{
[
	\clef<"g"> \meter<"4/4">
	\bow<"up">(g) 	\bow<"down">(a) \bow<"up">(e) 
	\bow<"down">(f e) \bow<"up">(a) \bow<"down">(e) \bow<"up">(f)
]
}
```

**Comment by dfober** [comment]
sorry, the online [guidoeditor](https://guidoeditor.grame.fr) has not been updated yet, nor the [guido doc](https://guidodoc.grame.fr)
I'll do it asap.

**Comment by arshiacont** [comment]
No problem.. take your time. The native version works _perfectly_! String players will thrive! :)

**Comment by dfober** [comment]
and there are new symbols in the guido font. The font version is now 3.8.
