### ISSUE TITLE
Display problems with harmony tag

### ISSUE THREAD

**Issue by yeonoson** [grame-cncm/guidolib#9]
With the newly merged harmony feature there are still some problems which are marked in the following image:

![guidolib-harmony](https://cloud.githubusercontent.com/assets/26634658/24429992/cc92eb30-1414-11e7-8cd0-b7cdc860c3fa.png)

- The harmony does not properly work with "autoBarlines=on", in this case the chord on first notes is put above the previous barline (which might even be on another page) -> As I'm always working with autoBarlines=off (by using the conversion output of libmusicxml), this problem does not affect me.
- Long chords (e.g. Cmaj7) might overlap the next chord (maybe some detection as done for lyrics might help)
- Currently the vertical position has to be set manually with e.g. 'dy=18', an automatic positioning (as done for lyrics) might be better. This one could also be handled when generating the gmn from musicxml.
- There might be a problem if a measure with 1 note has several chords. However, the horizontal position can be controlled by e.g. 'dx=10' (as done for the last E), but this is not yet used by the libmusicxml (see the second and third last chords - C, D)

**Comment by dfober** [comment]
Are these issues new i.e. did they appear with the last commit?
I've updated the sample gmn file in order to solve them manually but the issues are saved and I'll have a look asap. By the way and since this is a new tag, I could consider revising completely the design (font size, default position etc.) but I can't find any recommendation in the literature. Any idea about that?
ps: I invite you add your name to the contributors list (https://github.com/grame-cncm/guidolib/blob/dev/misc/Acknowledgments.txt)

**Comment by yeonoson** [comment]
These issues already existed on the harmony_tag branch but I've only been aware of some of them.

I don't know about any best practices for the styling of harmony information. However, I noted that all other rendering engines use a smaller font-size by default. Personally I like fsize=4 the most (default is fsize=6). See following screenshots for comparison:

MuseScore
![chord-text-comparison-musescore](https://cloud.githubusercontent.com/assets/26634658/24467898/a39c4314-14b6-11e7-9397-1abaf4d2ca4a.png)

Lilypond
![chord-text-compare-lilypond](https://cloud.githubusercontent.com/assets/26634658/24467910/abe0439a-14b6-11e7-90cf-4cbf83082ac1.png)

Guido
![chord-text-compare-guido](https://cloud.githubusercontent.com/assets/26634658/24467914/afd31342-14b6-11e7-9ad9-2bb656c9e1e0.png)

All the work in the harmony_tag branch has been contributed by @jfkilian. Maybe he knows more about the styling. 

As all I did was to rebase his branch to the current HEAD and to trigger the pull request, I won't put myself on the contributor list.

**Comment by jfkilian** [comment]
That harmony tag is a prototypical implementation, collision handling has not been addressed yet.

**Comment by dfober** [comment]
implementation has been revised
