### ISSUE TITLE
Slope explosion on long Slurs 

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#90]
Unit test:
```
{[ 
   (* meas. 44 *)  \key<-3> \slurBegin:1<curve="up"> \beamBegin:1 e&3/8. d/16 c/8 \beamEnd:1 \beamBegin:1 b&2/8. a&/16 g/8 \beamEnd:1 \bar 
   (* meas. 45 *)  \beamBegin:1 f/8. g/16 e/8 \beamEnd:1 \beamBegin:1 f/8. d&/16 d/8 \beamEnd:1 \bar 
   (* meas. 46 *)  \beamBegin:1 e&/8. f/16 d/8 \beamEnd:1 \beamBegin:1 e&/8. c&/16 d&/8 \beamEnd:1 \bar 
   (* meas. 47 *)  e&/4. b&1/8 \slurEnd:1 _/8 _/8 \bar 
   (* meas. 48 *)  _*3/4 \bar 
 ]
  }
```
This is a sample. We so this problem alot.

The slur height is too big and when put in a real score, this pattern persists and goes beyond its system bounding box as seen here:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/3298204/63900333-81eb4100-ca00-11e9-8ba3-a34c3b07f917.png">

**Comment by dfober** [comment]
a partial fix has been pushed to git
actually slurs need to be redesigned (which requires more time)

**Comment by dfober** [comment]
I think I can close this one now.
