### ISSUE TITLE
Include Hairpins and Text in System Bounding Box

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#93]
Hairpins and Text (among other things such as Intensity?) are not taken into account in the calculation of the System Bounding Box. 

This leads to overlap between systems. It can be corrected by hand-engineering but this would remove all the interest for an engine such as Guido! :) 

The following excerpt (from La Traviata) shows two examples of this (sorry for the crowded score!): 
- Hairpin on measure 11
- Hairpin on measure 25
are both on top of the system and can easily collapse with the higher system.

I reduced the score so that it would be more tractable! The 80 measure score becomes unreadable in this case on some measures.

[unit-boundingBoxExtension.gmn.txt](https://github.com/grame-cncm/guidolib/files/3656313/unit-boundingBoxExtension.gmn.txt)

**Comment by dfober** [comment]
I'll see what I can do asap. Note that you get very different results when 'Optimum page fill' is off.
This setting is 'on' by default but actually, it doesn't really make sense, especially in your case.
I'm not using it any more.

**Comment by arshiacont** [comment]
The problem persist despite Optimal Page Fill being off. The problem occurs mostly when you have dynamics and such "outside" the regular staff/system bounding box or at the borders. It happens often for voice with lyrics (cf. La Traviata example above).

PS: I have totally switched to https://guidoeditor.grame.fr/ ! Many kudos on that... will prepare xml2guido soon to integrate it there.

**Comment by arshiacont** [comment]
Here is a score sample that demonstrate the Bounding Box problem. Just load it inside https://guidoeditor.grame.fr/# for example: 
[SystemBoundingBox.gmn.txt](https://github.com/grame-cncm/guidolib/files/3821342/SystemBoundingBox.gmn.txt)

Below is the result of Page 1 and Page 2. While Page 2 is fine, Page 1 is messy. 

This is why I suggested we should integrate Slurs and Texts in the System Bounding Box but if there is another solution to this as a workaround it would be even better:

![SystemBoundingBox-Page1](https://user-images.githubusercontent.com/3298204/68420976-b9633000-019d-11ea-86c0-1938637479d3.png)
![SystemBoundingBox-Page2](https://user-images.githubusercontent.com/3298204/68420990-bf591100-019d-11ea-9012-5dce22dfbafe.png)
