### ISSUE TITLE
Cross Staff Slur incorrect positioning

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#94]
Unit test:
```
{[ \staff<1>  
   (* meas. 1 *)  \clef<"g2"> \key<-5> 
   _/16 \staff<2> \stemsUp \slurBegin:1<curve="up"> 
   \beamBegin:1 \beamBegin:2 f0/16 \stemsUp a&/16 
   \staff<1> \stemsUp d&1/16 \beamEnd:2 \beamEnd:1 \stemsUp \beamBegin:1 \beamBegin:2 f/16 
   \staff<2> \stemsUp a&0/16 
   \staff<1> \stemsUp d&1/16 
   \staff<2> \stemsUp f0/16 \beamEnd:2 \beamEnd:1 
   \staff<1> \stemsUp \beamBegin:1 \beamBegin:2 f1/16 
   \staff<2> \stemsUp a&0/16 
   \staff<1> \stemsUp d&1/16 \staff<2> \stemsUp f0/16 \beamEnd:2 \beamEnd:1 
   \staff<1> \stemsUp \beamBegin:1 \beamBegin:2 f1/16 
   \staff<2> \stemsUp a&0/16 
   \staff<1> \stemsUp d&1/16 
   \staff<2> \stemsUp f0/16 \slurEnd:1 
   \beamEnd:2 \beamEnd:1 ]
 , 
[ \staff<2> 
   (* meas. 1 *)  \clef<"f4"> \key<-5> {d&-1/1, d&0/1  } ]
  }
```

leads to: 
![image](https://user-images.githubusercontent.com/3298204/65757137-d3c5da80-e116-11e9-8c9f-428be1782774.png)

Expected: 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/3298204/65757154-de806f80-e116-11e9-8bbc-add49f5925ac.png">

**Comment by dfober** [comment]
This one is a bit tricky: actually, the slur is computed before the beaming, and since the beaming adjusts the length of the stems, the slur is computed with wrong bounding box information...

**Comment by arshiacont** [comment]
Complicated indeed!!! Let's move it to low-priority

**Comment by dfober** [comment]
Actually, solving the issue #105 should also solve this one (see the comment on #105)

**Comment by dfober** [comment]
Fixed! and pushed...
Slurs are now computed once the beaming is done. That solves also a lot of other issues.
