### ISSUE TITLE
Cross Staff Beaming Part 3

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#96]
Fresh new Unit test:
```
{[ \staff<1>  
   \clef<"g2"> \key<-5> \meter<"C"> 
   \staff<2> \stemsUp \slurBegin:1<curve="down"> \beamBegin:1 \beamBegin:2 a&0/16 \staff<1> e&1/16 g&/16 \staff<2> g&0/16 \slurEnd:1  \beamEnd:2 \beamEnd:1 
  \slurBegin:1<curve="down"> \beamBegin:1 \beamBegin:2 a&/16 \staff<1> d&1/16 f/16 \staff<2> f0/16 \slurEnd:1 \beamEnd:2 \beamEnd:1 
   \slurBegin:1<curve="down"> \beamBegin:1 \beamBegin:2 a&/16 \staff<1> d&1/16 f/16 \staff<2> f0/16 \slurEnd:1 \beamEnd:2 \beamEnd:1 
   \slurBegin:1<curve="down"> \beamBegin:1 \beamBegin:2 a&/16 \staff<1> d&1/16 f/16 \staff<2> f0/16 \slurEnd:1 \beamEnd:2 \beamEnd:1 \staff<1> \bar  ]
 , 
[ \staff<2> \clef<"f4"> \key<-5> {a&-2/1, a&-1/1} \bar ]
  }
```

leading to: 
![image](https://user-images.githubusercontent.com/3298204/65762443-518ee380-e121-11e9-83cf-f23b97ba3ea9.png)

Expected similar to:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/3298204/65762471-623f5980-e121-11e9-8080-8ab1c5cc69e0.png">

**Comment by dfober** [comment]
partial fix: beaming is now correct but the slurs are a bit ugly and there is still the missing clefs and signatures on first staff (a headache!). (pushed to github)

**Comment by dfober** [comment]
fully fixed and pushed
