### ISSUE TITLE
[question] Graphic mapping to pitch information

### ISSUE THREAD

**Issue by isaquevieira** [grame-cncm/guidolib#97]
Given a graphics mapping, how can I get the pitch information related to a graphic segment? For instance: for a graphic segment of a note, get the note pitch, octave, accidentals, measure and etc.
If there is no API for that, can you give me some direction on how to do that and contribute?

**Comment by dfober** [comment]
There is no API for all that. Actually, the information you get with the mapping (using `GuidoGetMap`) is a GuidoElementInfos struct i.e.
~~~~~
{
    GuidoElementType type;		///< the element type
    int   staffNum;	///< the element staff number or 0 when na
    int   voiceNum;	///< the element voice number or 0 when na
    int   midiPitch;     ///< the element midi pitch, or -1 when na
} GuidoElementInfos;
~~~~~
see GUIDOScoreMap.h
This struct could be extended, provided it does'n break the compatibility with previous versions. 
And of course, it requires to implement the methods to fill it.

Depending on what you want to do, I'm not sure that the good strategy is to extend the mapping interface. Maybe a new interface like `GuidoGetAtPoint(x, y)` returning an object that you can query could be more convenient.
