### ISSUE TITLE
Missing Intensity "fp"

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#98]
As seen wildly in classical repertoire:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/3298204/66765129-88981f80-eeab-11e9-8a9b-d196bddfa56b.png">

Adding `\intens<"fp">` would be very welcome! :)

**Comment by dfober** [comment]
That's done and pushed.
The corresponding font version is 3.9
