### ISSUE TITLE
Text and music fonts are generated with a predefined size

### ISSUE THREAD

**Issue by lucasanjosmoraes** [grame-cncm/guidolib#99]
When we are creating fonts to define on the device (GDisplayDeviceOSX specifically), we specify a size for each one. But it seems that GUIDO always renders a score with a predefined font size, regardless of the font type. Is this the expected behavior?

**Comment by dfober** [comment]
The music font is created with different sizes, depending on the use: e.g. notes for cues are smaller than regular notes. If you want to know exactly what happens at device level, you can use the guido2abstract tool (it uses a device that only print the call to the device api).
Does it answers your question?

**Comment by lucasanjosmoraes** [comment]
Yes, thank you
